### ISSUE TITLE
Install via go install

### ISSUE THREAD

**Issue by Elinvention** [matthieugrieger/mumbledj#101]
I saw that Go has this nice kind of package manager built-in. It would be awesome if MumbleDJ could be installed with a simple `go install github.com/matthieugrieger/mumbledj` instead of clone from git, cd, PATH=$GOPATH/bin/:$PATH make, make install. At the moment it can't compile as it fails with 
```
# github.com/matthieugrieger/mumbledj
./main.go:54: dj.client.AudioEncoder.SetApplication undefined (type gumble.AudioEncoder has no field or method SetApplication)
```
Thank you.

**Comment by matthieugrieger** [comment]
Yeah, that would be a good way to do it. The only issue is that MumbleDJ relies on non-Go dependencies, such as `youtube-dl`. I suppose MumbleDJ could check for these dependencies during run-time and alert the user about dependency requirement issues.

I am also looking into something like Docker, which could potentially even automate the installation of non-Go dependencies.

Long story short, I would definitely like to do this and will try to incorporate this change during the refactor I am currently working on. :)

**Comment by matthieugrieger** [comment]
This is now supported in v3.0.0.

**Comment by Elinvention** [comment]
Congratulations, for this awesome new release!

**Comment by matthieugrieger** [comment]
@Elinvention: Thanks! :)

Did you install using `go install`? If so, I'm curious to hear how it went.

**Comment by Elinvention** [comment]
Very well! But I had to run `go get` first, because go kept telling me that something was missing... Maybe something changed between go 1.5 and 1.6? Otherwise a blazing fast install.
I saw you switched config files to yaml format. Nice!

**Comment by matthieugrieger** [comment]
Great! Yeah, I'm not sure why `go get` needs to be run first, I've seen other projects that install the binary to `$GOPATH/bin` using just `go get`. I'll have to investigate this some more and see if I'm missing anything. Glad it works though!

And yeah, yaml format is *much* better than what was being used before.

**Comment by matthieugrieger** [comment]
@Elinvention: I just spun up a DigitalOcean droplet and tried installing MumbleDJ with just `go get -u github.com/matthieugrieger/mumbledj` and it placed a compiled executable in `$GOPATH/bin`. It doesn't appear that issuing the `go install` command is actually necessary.
