### ISSUE TITLE
Will you be requiring golang v1.5 soon?

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#102]
I see the 1.5 packages hitting my distro and it is another 150Mb. I was curious if you would keep requiring the newest go moving forward?

**Comment by matthieugrieger** [comment]
Since it seems most people run the bot on Ubuntu, a good rule of thumb would be to use the version of Go that Ubuntu supplies in its repos. I generally try to keep up to date.

Most often you will probably be fine using an older version of Go.
