### ISSUE TITLE
Mumbledj work on Arm like rasp ?

### ISSUE THREAD

**Issue by thenaing** [matthieugrieger/mumbledj#103]
Because i try 3 day to compile and i have always this : 

$/root/.mumbledj/config/mumbledj.gcfg
panic: Configuration load failed.

goroutine 1 [running]:
main.main()
        /home/me/mumbledj-2.8.4/main.go:250 +0xe24

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/me/.gvm/gos/go1.4/src/runtime/asm_arm.s:1322 +0x4

Somebody have same issues ?
I have go 1.4 install by gvm.

**Comment by matthieugrieger** [comment]
Can you verify that you have a file called `mumbledj.gcfg` in `~/.mumbledj/config`?

It looks like the bot compiled successfully, since you have to run the bot executable to get that error message.

**Comment by thenaing** [comment]
Thank !!!it work. Omg !! i am so bad some time.

Great job
Le 11 déc. 2015 12:04 AM, "Matthieu Grieger" <notifications@github.com> a
écrit :

**Comment by matthieugrieger** [comment]
Haha, no worries. I'm glad it's working now!
