### ISSUE TITLE
Wrong string output for currentsong command with a playlist

### ISSUE THREAD

**Issue by nkhoit** [matthieugrieger/mumbledj#108]
I'm trying to figure out what the intention of the string for CURRENT_SONG_PLAYLIST_HTML is because currently there are 3 arguments in the sprintf command and 5 specifiers in the string.

https://github.com/matthieugrieger/mumbledj/blob/master/strings.go#L204
https://github.com/matthieugrieger/mumbledj/blob/master/commands.go#L394-L395

**Comment by matthieugrieger** [comment]
Good catch! That is a mistake. I will be sure to fix it when I get the chance during the holidays. Thanks!
