### ISSUE TITLE
Freeze on !add and crash on !skip

### ISSUE THREAD

**Issue by MrKrucible** [matthieugrieger/mumbledj#11]
Finally decided to upgrade to the gumble version of your bot, and thank you very much for developing it! I've come across a similar problem to my first issue and it's happening on a Debian machine again.

Running !add freezes the bot up with no feedback. Typing out !skip when something isn't in queue gives me this dump. Just from looking at it I think I'm probably missing something Go related; go version gives out 1.4

Command used to start bot...
<code>$ mumbledj -server=mymumble -port=64738 -username=Data -password="" -channel=music
```
Channel doesn't exist or one was not provided, staying in root channel...
Configuration successfully loaded!
panic: runtime error: index out of range

goroutine 5 [running]:
main.skip(0xc20800cd00, 0xc208099250, 0xa, 0x0)
        /home/kirk/git/mumbledj/commands.go:205 +0xf58
main.parseCommand(0xc20800cd00, 0xc208099250, 0xa, 0xc2080f5111, 0x4)
        /home/kirk/git/mumbledj/commands.go:45 +0x317
main.(*mumbledj).OnTextMessage(0xc28760, 0xc2080fd490)
        /home/kirk/git/mumbledj/main.go:69 +0xce
main.*mumbledj.OnTextMessage·fm(0xc2080fd490)
        /home/kirk/git/mumbledj/main.go:117 +0x31
github.com/layeh/gumble/gumbleutil.Listener.OnTextMessage(0xc20802aac0, 0xc20802aad0, 0xc20802aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kirk/go/src/github.com/layeh/gumble/gumbleutil/listener.go:44 +0x37
github.com/layeh/gumble/gumbleutil.(*Listener).OnTextMessage(0xc208030320, 0xc2080fd490)
        <autogenerated>:3 +0xaa
github.com/layeh/gumble/gumble.eventMultiplexer.OnTextMessage(0xc20803d410, 0xc20803d440, 0xc2080fd490)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/eventmultiplexer.go:62 +0x57
github.com/layeh/gumble/gumble.handleTextMessage(0xc2080e0000, 0xc208033400, 0xc, 0x400, 0x0, 0x0)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/handlers.go:582 +0x917
github.com/layeh/gumble/gumble.(*Client).readRoutine(0xc2080e0000)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:204 +0x613
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:108 +0x434

goroutine 1 [chan receive]:
main.main()
        /home/kirk/git/mumbledj/main.go:128 +0x4ea

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0xc2080e0000)
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:163 +0x2dc
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/kirk/go/src/github.com/layeh/gumble/gumble/client.go:109 +0x451
kirk@kirk:~/git/mumbledj$ ```

**Comment by matthieugrieger** [comment]
Thanks for the bug report! 

The skip crash is something that can easily be fixed, and is a little thing I overlooked. 

For your add problem -- do you have `youtube-dl` installed? You shouldn't be missing anything Go related as the Makefile should take care of that for you. I'm pretty sure there is another user of the bot that is running it on Debian, so I don't think it is a problem with the distro.

I'll try to get a fix out for the skip crash ASAP, but I'm pretty busy today so it may be a little while.

**Comment by matthieugrieger** [comment]
I have closed the issue because I believe that your problem with the !add command is a setup issue, and most likely not a problem with the bot itself. My main suggestions would be to make sure that `youtube-dl` is installed, and that your server uses the Opus audio codec, not CELT.

If the issue happens to be with the bot then I will reopen this issue. Let me know if you get it working!

**Comment by MrKrucible** [comment]
Sorry for the late response, and yes youtube-dl is installed (did it via curl) with the Mumble server using the Opus codec.

I'm going to try and get the bot working on a different machine running Arch. Just to see if it's something going on with Debian.

**Comment by matthieugrieger** [comment]
@MrKrucible: No worries. I think there is somebody that I helped in the past that is using Debian for hosting MumbleDJ, and it seems to work fine for them. I can attest that the bot will work on Arch as it is the distro that I do all my testing on.

There may be some little caveats about the installation on Debian that I am missing. If you can't get it figured out I will try spinning up a Debian server to see if I can find the problem.

**Comment by MrKrucible** [comment]
Okay, just found out that the !add command works and it was just something going on with my VPS stalling packets. Got an email back with the VPS updated and the bot works perfectly.

Also I decided to just throw some more commands at the bot. What I found was all the skip related commands (<code>!skip, !skipplaylist, !forceskip, !forceskipplaylist</code>) crash MumbleDJ when nothing is in queue.

**Comment by matthieugrieger** [comment]
Awesome, glad you got it working! Have you tried updating to the newest release? It should have been fixed in this commit: https://github.com/matthieugrieger/mumbledj/commit/9667157d630874eaa28343561e1f432cb9e99820.

**Comment by MrKrucible** [comment]
Yup, got the latest release up and the bug is fixed. Thanks for developing again!

**Comment by matthieugrieger** [comment]
Nice! No problem!
