### ISSUE TITLE
Unable to use offsets if it's formatted as &t vs ?t in the URL.

### ISSUE THREAD

**Issue by fiveofeight** [matthieugrieger/mumbledj#111]
Currently if you try to use an offset such as: https://www.youtube.com/watch?v=8GznlD5jTqY&t=1m04s it does not work, it only works when formatted as https://youtu.be/8GznlD5jTqY?t=1m50s

https://github.com/matthieugrieger/mumbledj/blob/master/service_youtube.go#L91
Changing from:
`offset:    int(yt.parseTime(offset, `\?T\=(?P<days>\d+D)?(?P<hours>\d+H)?(?P<minutes>\d+M)?(?P<seconds>\d+S)?`).Seconds()),`
to 
`offset:    int(yt.parseTime(offset, `T\=(?P<days>\d+D)?(?P<hours>\d+H)?(?P<minutes>\d+M)?(?P<seconds>\d+S)?`).Seconds()),`
resolves the issue.

**Comment by matthieugrieger** [comment]
Ah, good catch. Would you mind making a pull request for this?

**Comment by fiveofeight** [comment]
Done.
