### ISSUE TITLE
[Feature-request] Add video player instead video image when !add command is used

### ISSUE THREAD

**Issue by jonybravo30** [matthieugrieger/mumbledj#114]
It would be awesome "add" command to send the video with the player instead of the video image so you could play the video within the mumble . Would it be possible ?

Another cool feature would add the "image " command, then the bot will search for the first occurrence of that word, i.e. he could find in google image and stick the picture on the mumble chatbox.

i.e.: !image  he-man 

 Thank you very much , you make a very cool job.

**Comment by mkody** [comment]
>It would be awesome "add" command to send the video with the player instead of the video image so you could play the video within the mumble . Would it be possible ?

Nope, Mumble doesn't allow that. You can't embed content in the chat, [since `<iframe>` or `<embed>` isn't available on qt5.](http://doc.qt.io/qt-5/richtext-html-subset.html)

>Another cool feature would add the "image " command, then the bot will search for the first occurrence of that word, i.e. he could find in google image and stick the picture on the mumble chatbox.

Well, this project is for making a bot that plays audio _only_. A quick search on GitHub may help you! :)

**Comment by joncolas** [comment]
okay, thanks!

**Comment by jonybravo30** [comment]
okay, thanks!

**Comment by matthieugrieger** [comment]
@mkody: Thanks for the response, you're exactly right.

@jonybravo30: The `!image` command is a bit out of scope for MumbleDJ, but feel free to fork the repository and code it up yourself!
