### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by raz0rsdge** [matthieugrieger/mumbledj#12]
On CentOS as non-privileged user I get this error while make, I couldn't find out where the build-process is searching for the opus.h file since gopus.h simply includes opus.h from which path?:

go get -u github.com/layeh/gumble/gumble
# github.com/layeh/gopus
In file included from ../src/github.com/layeh/gopus/decoder.go:4:
gopus.h:1:18: error: opus.h: No such file or directory

**Comment by bontibon** [comment]
The Opus development library/headers needs to be installed on your system.  You can do this by running using:

    yum install opus-devel

**Comment by matthieugrieger** [comment]
Thanks @bontibon! I would have replied to this sooner but I was in class. His suggestion should fix your problem, @raz0rsdge. Let me know if there are still issues.

**Comment by raz0rsdge** [comment]
Okay thanks I fixed it, since there is no install available to me as user, I used toast to get opus and ffmpeg installed to my user environment, now all works fine! 

Again, thanks for the awesome work ;)
