### ISSUE TITLE
Download failure message not well formatted

### ISSUE THREAD

**Issue by GabrielPlassard** [matthieugrieger/mumbledj#120]
The 'AUDIO_FAIL_MSG' is supposed to contain the name of the song which failed, but the fmt.Sprintf function is not used, which leads to '%s' to be displayed instead.

https://github.com/matthieugrieger/mumbledj/blob/master/strings.go#L63
https://github.com/matthieugrieger/mumbledj/blob/master/songqueue.go#L121
https://github.com/matthieugrieger/mumbledj/blob/master/service.go#L126

`const AUDIO_FAIL_MSG = "The audio download for this video failed. %s has likely not generated the audio files for this %s yet. Skipping to the next song!"`

I'm not quite sure what is supposed to be displayed in place of the second '%' though? 

I'll try to have a look this week-end

**Comment by matthieugrieger** [comment]
Nice catch, this is a bug. I will try to get to this sometime soon unless you get to it before me. :)

**Comment by GabrielPlassard** [comment]
I just need to know what you want to display in place of the second '%s' and I could do it.

**Comment by matthieugrieger** [comment]
The second `%s` can just be removed. Just replace it with the word "track".

**Comment by matthieugrieger** [comment]
Thanks for the fix!
