### ISSUE TITLE
MumbleDJ does not have a valid YouTube/Soundcloud API key.

### ISSUE THREAD

**Issue by Perdouille** [matthieugrieger/mumbledj#127]
Hey !

I'm trying to setup MumbleDJ on my own Mumble server. Both are hosted on my Raspberry Pi.

I've installed everything, the bot can connect and send messages on the server, but when I add a music with the !add command, I got a message saying that MumbleDJ doesn't have a valid API key.

I've set the Youtube API key in the file like in the README and the key seems to be working (https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=OglS3Q0Zxik&key=[MY KEY] (I found the url in another issue post on this repo) gives me something that isn't an error, I tried from a web browser directly on the Pi) 

I just have to set the key in the file, right ? 

I'm running MumbleDJ under root, and I tried downloading vids directly with youtube-dl, it's working.

Thanks for your help ! 

Edit : 

When I do "curl "https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=OglS3Q0Zxik&key=[MY KEY]"", I get videos names and thumbnails links and stuff, but it is still not working with MumbleDJ.

Soundcloud API key doesn't seems to work either

Edit2 : Here is the "make" logs : 

https://zerobin.net/?4a12ef4087a644eb#nX1qWjdb1qv/wVoamXT9Ljypvu32GLFBnn7Oj5TTUm0=

Is the "can't load package: package github.com/timshannon/go-openal: no buildable Go source files in /home/pi/2mumbledj/mumbledj/.vendor/src/github.com/timshannon/go-openal" normal ?

**Comment by matthieugrieger** [comment]
Yes, you have to set the API keys in the config file.

Make sure that you are putting your API keys in the config file within `~/.mumbledj/config` rather than in the directory that you cloned. If you make edits in the config file within your cloned directory it won't reliably migrate your changes to `~/.mumbledj/config`. It is something I've been meaning to fix.

**Comment by Perdouille** [comment]
Yes they are set in the "~/mumbledj/config/mumbledj.gcfg", at the end

[ServiceKeys]
YouTube = "MY KEY"
SoundCloud = "MY OTHER KEY"

It is the good file because if I edit something else it does change (And if I remove both keys it doesn't start)

**Comment by matthieugrieger** [comment]
It is unlikely that it has to do with the `make` errors but it wouldn't hurt to take a look. Could you post those?

**Comment by Perdouille** [comment]
I posted those here : https://zerobin.net/?4a12ef4087a644eb#nX1qWjdb1qv/wVoamXT9Ljypvu32GLFBnn7Oj5TTUm0=

**Comment by matthieugrieger** [comment]
Whoops, sorry, didn't see that. Everything in the logs seems fine to me.

Could you post the contents of your config file on zerobin or pastebin?

**Comment by Perdouille** [comment]
Even the 
 can't load package: package github.com/timshannon/go-openal: no buildable Go source files in /home/pi/2mumbledj/mumbledj/.vendor/src/github.com/timshannon/go-openal can't load package: package github.com/golang/protobuf: no buildable Go source files in /home/pi/2mumbledj/mumbledj/.vendor/src/github.com/golang/protobuf
 ?

Here's the config file (Found at ~/.mumbledj/config/mumbledj.gcfg) : https://zerobin.net/?02c33a3e9d858115#dHpB6sbebw1fFF+x9gst3n8NFoz0Q4KPrIyWoRYK3fw=

**Comment by matthieugrieger** [comment]
Yes, those are fine. They aren't used directly by MumbleDJ so if you successfully get a compiled binary (it appears you have), there isn't anything to worry about there.

Let me get back to you on this. If you haven't already, take a look through the closed issues related to this one (I know there are some) and see if any of the solutions in those threads work for you.

**Comment by Perdouille** [comment]
Yes I already tried pretty much everything I could find :/

Is there any way to have some logs or something ? Like a "verbose" or a "debug" mode

**Comment by matthieugrieger** [comment]
Not really with the current code unfortunately. I started a refactor to fix this issue and a few others but I haven't had a whole lot of time to work on it (and motivation, to be quite honest).

Could you tell me what other things you tried? This will help me narrow it down.

**Comment by Perdouille** [comment]
I tried pretty much everything I could find, I don't have the exact list :/

But anyway, I changed the server (Went from my Raspberry to a 64 bits CPU) and now it's working.That's weird

Thanks for helping :)

**Comment by matthieugrieger** [comment]
Oh, weird. It seems like there's a lot of strange issues with MumbleDJ on Raspberry Pis for some reason.

Glad you resolved it one way or another!
