### ISSUE TITLE
Error message while executing make

### ISSUE THREAD

**Issue by TomStary** [matthieugrieger/mumbledj#130]
I've got this error message on my RPi 3
pkg-config --cflags opus
Package opus was not found in the pkg-config search path.
Perhaps you should add the directory containing `opus.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opus' found
pkg-config: exit status 1
goop: Command failed with exit status 2

**Comment by DudeofA** [comment]
Sound like you don't have opus installed or the path isn't set up correctly

**Comment by TomStary** [comment]
Thanks, manage to get everything that I need and successfully installed that

**Comment by azlux** [comment]
There are only opus-tools on debian.
Do I search on the place ?

**Comment by matthieugrieger** [comment]
@azlux: `libopus-dev` is likely what you'll want on Debian.

**Comment by azlux** [comment]
@matthieugrieger : yes, but even if it's installed, I still have the error

**Comment by azlux** [comment]
thank

**Comment by matthieugrieger** [comment]
@azlux: Does it work now?

**Comment by azlux** [comment]
Yes thank
