### ISSUE TITLE
Connection timed out on add mixcloud urls

### ISSUE THREAD

**Issue by AcidZ3r0** [matthieugrieger/mumbledj#135]
Hello.
I try to add mixcloud songs, but mumbledj freezes on this. Hes download 4-5 mbytes and stop. I down mumblejd process and run hes again, he download other 4-5 mbytes and stop again. I do this 10-12 times, and song full downlolad on cache, and dj play him.
I run mumbledj on strace and see this on logs
`futex(0xda2d08, FUTEX_WAIT, 0, NULL)    = 0
futex(0xda2d08, FUTEX_WAIT, 0, NULL)    = 0
futex(0xc820158108, FUTEX_WAKE, 1)      = 1
futex(0xda1f18, FUTEX_WAIT, 0, {9, 999929082}) = -1 ETIMEDOUT (Connection timed out)
futex(0xda2370, FUTEX_WAKE, 1)          = 1
futex(0xda22b0, FUTEX_WAKE, 1)          = 1
futex(0xc820062108, FUTEX_WAKE, 1)      = 1
futex(0xc820158108, FUTEX_WAKE, 1)      = 1
futex(0xda1f18, FUTEX_WAIT, 0, {9, 999643126}) = -1 ETIMEDOUT (Connection timed out)
`
UPD
Sorry for my bad english.

**Comment by matthieugrieger** [comment]
Hmm.. according to this issue it seems that Mixcloud may be throttling download speeds: https://github.com/rg3/youtube-dl/issues/3448

The person who filed the above issue seems to experience slowdowns at around 4MB as well.

I'll have to take a look at this and see if there are any ways to get around it. Does anybody else have this issue?

**Comment by AcidZ3r0** [comment]
```
youtube-dl -v https://www.mixcloud.com/maxvibes/record-kicks-special/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.mixcloud.com/maxvibes/record-kicks-special/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.6 - Linux-3.19.0-58-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-79139-gde1a0d4, ffprobe N-79139-gde1a0d4
[debug] Proxy map: {}
[mixcloud] maxvibes-record-kicks-special: Downloading webpage
[mixcloud] maxvibes-record-kicks-special: Trying mp3 URL
[mixcloud] maxvibes-record-kicks-special: Trying m4a URL
[debug] Invoking downloader on u'https://stream21.mixcloud.com/c/m4a/64/8/e/a/9/ae76-ea61-4145-a6b5-930577a12be2.m4a'
[download] Destination: Record Kicks special-maxvibes-record-kicks-special.m4a
[download]  11.8% of 33.79MiB at  5.18MiB/s ETA 00:05
```

And freeze. 

> https://github.com/rg3/youtube-dl/issues/3448

Yes, it's my trouble too.

**Comment by matthieugrieger** [comment]
Thanks. I'll have to take a look around and see if there is any way to resolve this.

**Comment by johnydevops** [comment]
i was doing some tests using debian package named `tickle`(apt-get install tickle) in order to manage the bandwidth used by mumbledj/youtube-dl process, so:

```
trickle -s -d 650 youtube-dl --verbose --no-mtime --output /home/ubuntu/.mumbledj/songs/record-kicks-special.best --format best --prefer-ffmpeg https://www.mixcloud.com/maxvibes/record-kicks-special/


[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--no-mtime', u'--output', u'/home/ubuntu/.mumbledj/songs/record-kicks-special.best', u'--format', u'best', u'--prefer-ffmpeg', u'https://www.mixcloud.com/maxvibes/record-kicks-special/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.6 - Linux-3.13.0-36-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, ffmpeg 2.7, ffprobe 2.7, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] maxvibes-record-kicks-special: Downloading webpage
[debug] Invoking downloader on u'https://stream13.mixcloud.com/c/m4a/64/8/e/a/9/ae76-ea61-4145-a6b5-930577a12be2.m4a'
[download] Resuming download at byte 4193280
[download] Destination: /home/ubuntu/.mumbledj/songs/record-kicks-special.best
[download] 100.0% of 33.79MiB at 23.89KiB/s ETA 00:00ERROR: unable to rename file: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 193, in try_rename
    os.rename(encodeFilename(old_filename), encodeFilename(new_filename))
OSError: [Errno 2] No such file or directory
```

Finally i get the download finished after 20 minutes aprox, at speed of 25 Kb/s, but it seems that youtube-dl must have some problems with the new filename generated.

Some ideas?

**Comment by matthieugrieger** [comment]
Thanks, @johnydevops. It appears that Mixcloud is most likely throttling download rates on their end. Not sure if there is a way around this, hopefully I can get a look at it fairly soon.

**Comment by matthieugrieger** [comment]
I added a possible workaround for this issue in v3.0.0 by using `aria2`. Try it out and open another issue if you're still having problems.
