### ISSUE TITLE
Process Ends are Starting

### ISSUE THREAD

**Issue by dskaplan** [matthieugrieger/mumbledj#137]
Hi, I've been really enjoying your creation.

I had the DJ running on a virtualbox (Mint 14.04) for a while and everything was great. One day, and not with any changes I am aware of (to either the box or the server), it failed to connect.
I enter the credentials and see:
```
Configuration successfully loaded!
Could not connect to MUmble server at -servername-
```
I figured I'd try to connect to a few different servers and also running it from my main machine (OSX 10.11). You briefly alluded to the problem [here](https://github.com/matthieugrieger/mumbledj/issues/74) and I was wondering if you have any new insight?

Thanks.

**Comment by matthieugrieger** [comment]
Have you tried running the bot with the `-insecure` flag?

**Comment by dskaplan** [comment]
Thanks for the response!

`./mumbledj -insecure -server=.....etc`

Putting it at the start or the end didn't change anything. Hm.

**Comment by dskaplan** [comment]
@matthieugrieger: I wanted to update you, I clean installed a Mint virtualbox and used the insecure flag. That worked (the above reply was based on the OSX instance). I am sorry I can't provide any insight as to why, but I am guessing this hasn't been utilized on OSX much (make install uses some flags that OSX doesn't understand without CoreUtils installed).

Thanks agian for the help.

**Comment by matthieugrieger** [comment]
Ah, that makes sense. Thanks for the update.

I haven't done any testing on OSX so I'm not quite sure how MumbleDJ behaves on it.
