### ISSUE TITLE
Adding a YouTube playlist only adds the first YouTube video to the que

### ISSUE THREAD

**Issue by chriseilander** [matthieugrieger/mumbledj#139]
Shouldn't an admin be able to add a whole playlist to the que if he wanted? Now only the first song of the playlist is added...

**Comment by matthieugrieger** [comment]
I'll have to test this out myself as I have never experienced this issue.

Does this happen with all YouTube playlist URLs? Did it just start happening recently?

**Comment by chriseilander** [comment]
I only recently start using mumbledj. So far all playlist links give this problem. I tried several public ones. 

The setting about how much video's from a play list that can be added is at its default setting (which is 50 I believe?)

**Comment by matthieugrieger** [comment]
Hmmm... yeah that shouldn't be limiting the number of videos you get in a playlist then. I'll have to check it out on my own server when I have the time.

**Comment by BudgieInWA** [comment]
Are you trying to add a playlist via a url that looks like `https://www.youtube.com/watch?v=OPf0YbXqDm0&list=RDOPf0YbXqDm0#t=4`? Myself and others expected that to add the playlist, but it is treated as a song URL, not a list URL.

**Comment by matthieugrieger** [comment]
I'm guessing what @BudgieInWA mentioned is what was happening.

In any case, I've tested adding playlists myself and it works fine.

**Comment by chriseilander** [comment]
I did think that was what happend, I expected it to work since that link also goes to the playlist. So if that is not it, how can you find the correct playlist link of, for example, the playlist posted by @BudgieInWA ?

**Comment by matthieugrieger** [comment]
@chriseilander: The link that @BudgieInWA posted was a link to a YouTube Mix, which is a bit different than a playlist. YouTube Mixes are (to my knowledge) procedurally generated and do not have a set length, meaning they aren't really "playlists".

This is an example of a URL that will work: https://www.youtube.com/playlist?list=PLyjgHc47unfT3BIZo5uEt2a-2TWKy54sU

It is a user-created playlist so it is supported by the bot. I'll have to look into the YouTube API to see if the bot can also support mixes.

**Comment by chriseilander** [comment]
Ah no in nu case it was a usergenerated list, not a YouTube mix.

**Comment by BudgieInWA** [comment]
I think playing a normal playlist gives you the same type of URL as playing
a Mix. I don't know if the interface gives you a link to the playlist page.

From the search results page, the playlist title links to the first video
and you need to click on the "see all videos" link to get to the playlist
page. I had clicked on the playlist title and used that URL when I tried
and failed.

**Comment by matthieugrieger** [comment]
Yeah, you have to have a URL of the following format to add a playlist to the queue from YouTube:
```
youtube.com/playlist?list={playlist}
```

@BudgieInWA: I don't think YouTube Mixes are treated the same way as user-created playlists. For example, if you take the URL you posted above and modify it to look like the playlist format, you get this: https://www.youtube.com/playlist?list=RDOPf0YbXqDm0. This URL returns an error. If you do this same process with a video from a user-generated playlist doing this would not return an error.

@chriseilander: While not as convenient as it could be, if you have a link of the form you described you can always alter it to the format I stated above and it should add the whole playlist.
