### ISSUE TITLE
Debian 7 Problem

### ISSUE THREAD

**Issue by caindrac** [matthieugrieger/mumbledj#141]
Just to let you know I can not get this to run on Debian 7. I am have been trying track down the problem but I can't figure it out. I am guessing has something to do with Opus but I am not sure. It takes request but does not play the audio. I have been able to spin up another VM on my machine and it works perfect on Ubuntu.

**Comment by matthieugrieger** [comment]
Do you have `ffmpeg` or `avconv` installed on your Debian system?

**Comment by caindrac** [comment]
I have attempted both to try to get it working.

**Comment by matthieugrieger** [comment]
Try using the newer version of MumbleDJ. I believe a lot of the installation issues have been ironed out. If it still doesn't work, let me know.
