### ISSUE TITLE
!move feature

### ISSUE THREAD

**Issue by azlux** [matthieugrieger/mumbledj#142]
hi,
I'm think about a new feature. Instead of !move <channel/sub-channel...> can be possible to have a command !joinme where the bot join the channel where you are ?

Thank a lot for the bot, it's awesome !

Az

**Comment by matthieugrieger** [comment]
Good idea! Currently the bot only scans comments in the channel it is currently residing in, so it is possible that this would not be possible.

However, if it was a private message to MumbleDJ it would most likely work across channels.

I'll take a look at it as soon as I can.

**Comment by azlux** [comment]
Indeed, I was thinking about private message. ( I'm trying to make a mumo script to do that when the message is in the user channel, but the doc is missing)
It's will be mode user-friendly than !move chanel/subchannels command

**Comment by azlux** [comment]
Done it, I will pull the code this evening.
I took the command !joinme
Working so good

**Comment by azlux** [comment]
did I fork/pull your master or refractor ? what do you prefer ?

**Comment by matthieugrieger** [comment]
Nice! Master would be great. I'm not sure what the ETA for the refactor branch being merged into master is. I'll simply incorporate your changes in the refactor branch later.

**Comment by matthieugrieger** [comment]
This feature has been implemented by @azlux. Thanks again!
