### ISSUE TITLE
linked channel

### ISSUE THREAD

**Issue by azlux** [matthieugrieger/mumbledj#143]
Hi,
Real issue this time, bot don't send message when we are into the same linked channel. (the channel is linked with others.

Az.

**Comment by matthieugrieger** [comment]
Thanks for the report. I'll take a look at it when I get the chance.

**Comment by azlux** [comment]
OK, you can close this issue.
One of my admin have create LCA to avoid the boot to speak !

Srry for that
Az

**Comment by matthieugrieger** [comment]
No problem, let me know if there are any other issues.
