### ISSUE TITLE
Gopus build errors on FreeBSD

### ISSUE THREAD

**Issue by mheppner** [matthieugrieger/mumbledj#144]
After installing opus-1.1.2, opus-tools-0.1.9, and go-1.6.2, I try to run `make build`, but it fails with error messages about gopus. I'm not sure if I should report this on `layeh/gopus` instead. The C compiler is Clang 3.4.1. I don't know enough about Go to figure out what it's failing on, but here are the last few lines:

```
/tmp/go-build789578334/github.com/layeh/gopus/_obj/opus_nonshared.cgo2.o: In function `logSum':
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:212: undefined reference to `floorf'
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:212: undefined reference to `floorf'
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:212: undefined reference to `floorf'
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:212: undefined reference to `floorf'
/tmp/go-build789578334/github.com/layeh/gopus/_obj/opus_nonshared.cgo2.o: In function `surround_analysis':
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:323: undefined reference to `log'
/tmp/go-build789578334/github.com/layeh/gopus/_obj/opus_nonshared.cgo2.o: In function `FLOAT2INT16':
.vendor/src/github.com/layeh/gopus/opus-1.1.2/celt/float_cast.h:136: undefined reference to `lrintf'
/tmp/go-build789578334/github.com/layeh/gopus/_obj/opus_nonshared.cgo2.o: In function `tansig_approx':
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/mlp.c:88: undefined reference to `floorf'
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/mlp.c:88: undefined reference to `floorf'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
goop: Command failed with exit status 2
*** Error code 2
```

The output of `pkg-config --cflags opus` gives `-I/usr/local/include/opus`, which should mean that the Opus header files can be found, correct? There is an `opus.h` in that folder. It seems a lot of the undefined references are to math functions like pow, floor, cos, log, etc. How would I know if the math library is being linked (usually done with a compiler flag of `-lm`)?

**Comment by matthieugrieger** [comment]
Yeah, I think you might have more luck if you report this to https://github.com/layeh/gopus. Let me know if you figure something out!

It does seem like the math library isn't getting linked correctly.

**Comment by mheppner** [comment]
I'll report it over there, thanks. I'll let you know if any changes affect this repo or if there are installation instructions to add specific to FreeBSD.

**Comment by mheppner** [comment]
[Fixed](https://github.com/layeh/gopus/commit/867541549ca5f8b4db2b92fd1dded8711256a27d)

**Comment by matthieugrieger** [comment]
Wow, that was fast! Glad it's fixed now. :)
