### ISSUE TITLE
Can't get make to work. No buildable Go source files?

### ISSUE THREAD

**Issue by epilimic** [matthieugrieger/mumbledj#145]
Hello,
When I try running "make" I run into a couple problems. I'm on Debian 8.

> can't load package: package github.com/golang/protobuf: no buildable Go source files in /home/myuser/mumbledj/.vendor/src/github.com/golang/protobuf
> 
> can't load package: package github.com/timshannon/go-openal: no buildable Go source files in /home/myuser/mumbledj/.vendor/src/github.com/timshannon/go-openal
> 

The location is wrong and I don't see where to edit it to the correct one. From what I can tell, it should be in .../protobuf/proto and .../go-openal/openal respectively.

Here's my full log: http://pastebin.com/R9frG0fe

I've tried adding both of those packages with goop using these commands:

> goop go get github.com/timshannon/go-openal/openal
> goop go get github.com/golang/protobuf/proto

I can't symlink it because the folder name is the same as the destination:

> ln: failed to create symbolic link ‘./openal’: File exists

I tried adding a couple mv lines to move the files over during the install but it appears goop wipes and re-downloads those folders every time I run make.

What can I do to get it to point to the correct locations so I can get this installed?

**Comment by epilimic** [comment]
Small update (still not working though): I followed the instructions by Redyz here: https://github.com/matthieugrieger/mumbledj/issues/124#issuecomment-210738305

I appended github.com/timshannon/go-openal and github.com/golang/protobuf to the bottom of the goopfile, then edited the main.go and cache.go as he said, and now this is my output:

http://pastebin.com/mdedpwMT

**Comment by matthieugrieger** [comment]
I will investigate this once I get the chance. I am in the midst of university finals so it will be a few days unfortunately.

**Comment by epilimic** [comment]
After updating Go from 1.5 to 1.6.2 I was able to successfully compile it. I did still see the errors regarding the missing files, however it appears to work fine in mumble.

**Comment by matthieugrieger** [comment]
Oh, well that's good! I will be sure to suggest that if someone else has the same issue.

I have been working on a complete refactor of the bot that is getting fairly close to completion, so hopefully these issues will all be sorted out with a new code base. I'm getting rid of goop and will be using the official Go vendoring.

**Comment by epilimic** [comment]
Sounds good. Thanks for the bot!
