### ISSUE TITLE
Option to pause?

### ISSUE THREAD

**Issue by epilimic** [matthieugrieger/mumbledj#146]
Just a feature request... it would be great if you could add a !pause and !resume / !unpause to the bot. If people are listening to stuff that isn't necessarily music, like long podcasts, that'd be super helpful. Thanks!

**Comment by matthieugrieger** [comment]
It'll be coming soon. :)

**Comment by azlux** [comment]
hooo would be so great !

**Comment by epilimic** [comment]
Thanks, looking forward to it!

**Comment by matthieugrieger** [comment]
Implemented `!resume` and `!pause` in v3.0.0.
