### ISSUE TITLE
Flux feature

### ISSUE THREAD

**Issue by azlux** [matthieugrieger/mumbledj#147]
I know you use youtube-dl, but do you think it will be possible to play a flux instead of a file ?
I think it's will be great if we can add radio url into the bot. 
I know it's not in the current implementation way.

I'm thinking about flux from IceCast for example.

**Comment by matthieugrieger** [comment]
It may be possible to do streams through IceCast. Supporting radio would be a cool feature!

**Comment by azlux** [comment]
Just to be sure, I'm thinking about be connected to a flux to play it, not the mumbledj becoming a web radio. (IceCast was a example, it will be great if mumbledj could play any mp3/ogg flux)

**Comment by matthieugrieger** [comment]
Could you clarify what "connected to a flux" means, then? I'm not familiar with that terminology. I googled around but couldn't find anything.

Do you mean a stream?

**Comment by azlux** [comment]
Indeed, you have find the good meaning. I always speak about audio flux, but stream is the good word. Sorry for my english.

**Comment by matthieugrieger** [comment]
No worries!

**Comment by UdoKifferbrehl** [comment]
Yes, radio would be awesome (e.g. http://listen.technobase.fm/) 😍

**Comment by azlux** [comment]
So, after reading you code. I maybe not a go professional, but implementing this feature will break your code structure because you download and read the file downloaded after that. That is the opposite of a stream.
I think I will make a separated bot for radio steam.

**Comment by matthieugrieger** [comment]
Yes, that is true. I'm also not sure if Gumble supports it either.

**Comment by azlux** [comment]
Done ! 
@UdoKifferbrehl @matthieugrieger 
https://github.com/azlux/MumbleRadioPlayer
Sorry it's not in golang but in python :D But it's working well

**Comment by matthieugrieger** [comment]
Wow, nice!

**Comment by mkody** [comment]
FYI, we can have an audio stream from an Icecast source with Gumble. I've done it (and, well, I hardcoded the URL actually) through the gomumblesoundboard project. [Here's my fork and the highlighted lines.](https://github.com/mkody/gomumblesoundboard/blob/master/gomumblesoundboard.go#L86-L92)

**Comment by matthieugrieger** [comment]
@mkody: Oh, great! Thanks.

I'll take a look at it.
