### ISSUE TITLE
string and translation

### ISSUE THREAD

**Issue by azlux** [matthieugrieger/mumbledj#152]
#### What type of issue is this?
- [ ] Bug report (encountered problems with MumbleDJ)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other:

#### Description of your issue:
Hi, I've just try your new version. why have you abandoned the String.go file. I think it's better to have strings into one file, it's better when people want to translate your project..

**Comment by matthieugrieger** [comment]
I apologize for getting rid of the strings file. I'm currently contemplating better ways to organize the strings, as that file was an unorganized mess before.

Putting back something similar to the `strings.go` file is definitely on the to-do list.

**Comment by matthieugrieger** [comment]
I've decided to put these strings in the `config.yaml` file. Does that sound good to you?

**Comment by matthieugrieger** [comment]
@azlux: Try updating to v3.0.1. After installing the update, run MumbleDJ and it should generate a `config.yaml.new` file in your `~/.config/mumbledj` directory. Replace `config.yaml` with this file and you should be able to do your translations there!
