### ISSUE TITLE
Force skipping while there's no queue results in distorted songs

### ISSUE THREAD

**Issue by chauffer** [matthieugrieger/mumbledj#156]
Steps to reproduce:

- !add https://www.youtube.com/watch?v=DLzxrzFCyOs
- !fs
- The current track has been forcibly skipped, however, it does not stop.
- !add https://www.youtube.com/watch?v=DLzxrzFCyOs
- Robot rickroll

**Comment by matthieugrieger** [comment]
Are video downloads working for you currently? I'm trying to test this but all `youtube-dl` downloads are failing for me at the moment.

**Comment by chauffer** [comment]
They are, but I installed it this way:

```
sudo curl -L https://yt-dl.org/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by matthieugrieger** [comment]
Strange, that's how I installed it as well... For me YouTube downloads aren't working on both my local VM and on my server.

**Comment by chauffer** [comment]
What issue are you seeing?

**Comment by matthieugrieger** [comment]
It was a strange issue on my end. It went away. Fixed the issue, pushing now...

**Comment by chauffer** [comment]
Thank you! 
Are you on IRC by any chance?

**Comment by matthieugrieger** [comment]
I am not unfortunately. I should get a channel set up at some point...

If you need to contact me outside of GitHub the easiest would either be Twitter ([@matthieugrieger](https://twitter.com/matthieugrieger)) or via Email (me@matthieugrieger.com).

**Comment by matthieugrieger** [comment]
@chauffer: I created a [gitter chat room](https://gitter.im/matthieugrieger/mumbledj) for MumbleDJ. I may switch to something else later if I don't like it.

I added a badge for the gitter chat to the README as well.
