### ISSUE TITLE
[Feature request] Enable any configuration property to be overriden from the command line 

### ISSUE THREAD

**Issue by GabrielPlassard** [matthieugrieger/mumbledj#158]
It would be really cool to be able to overwrite any configuration property directly from the command line like

mumbledj --cache.enabled=true --api_keys.youtube=key
or
mumbledj --set "cache.enabled=true,api_keys.youtube=key"

Thanks a lot :)

**Comment by matthieugrieger** [comment]
I hope to implement this soon. I think I *might* have thought of a way to support this feature with functionality similar to your first example.

**Comment by matthieugrieger** [comment]
I was actually able to work on this today, and I think it works pretty well. Let me know if you come across any issues while messing around with it. :)

**Comment by GabrielPlassard** [comment]
Awesome, thank you very much! I just played a little with it and it seems to work!
