### ISSUE TITLE
2.2.5 make process

### ISSUE THREAD

**Issue by raz0rsdge** [matthieugrieger/mumbledj#16]
Okay today I'm getting this while trying to make V2.2.5, anyone else getting this error?
<b>
./commands.go:156: invalid operation: shortUrl != nil (mismatched types string and nil)
make: *** [mumbledj] Error 2</b>

**Comment by matthieugrieger** [comment]
Whoops! That's a bug. Thanks for pointing that out!

**Comment by raz0rsdge** [comment]
Thank you for that quick response ;)
