### ISSUE TITLE
Problem with the queue when MumbleDJ gets kicked

### ISSUE THREAD

**Issue by Perdouille** [matthieugrieger/mumbledj#161]
#### Before submitting this issue, please acknowledge that you have done the following:
- [X] I've at least skimmed through the [README](https://github.com/matthieugrieger/mumbledj/blob/master/README.md)
- [X] I have checked that I am running the latest version of MumbleDJ (use `mumbledj --version` when starting the bot or use the MumbleDJ version command in Mumble)
- [X] I have [searched through the existing issues](https://github.com/matthieugrieger/mumbledj/issues) to see if my issue has been answered already

---

#### What type of issue is this?
- [X] Bug report (encountered problems with MumbleDJ)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other:

---

#### Log output of bot with `--debug` flag (likely only for bug reports):
```
INFO[0000] Attempting connection to server...            address=127.0.0.1 port=1234
INFO[0001] Setting default volume...                     volume=0.20
INFO[0001] Caching disabled.
INFO[0007] A user has disconnected or changed channels, updating skip trackers...  user=MumbleDJ
INFO[0024] Sending a message to channel...               channel=Salon 1 
message=<b>Perdouille</b> added <b>1</b> track to the queue: YOUTUBE VIDEO 1
* Plays video 1 *


*Getting kicked, comes back and play nothing*
INFO[0044] A user has disconnected or changed channels, updating skip trackers...  user=MumbleDJ
WARN[0044] Disconnected from server. Retrying connection...  attempts=10 interval_secs=5
INFO[0044] Retrying connection...
INFO[0045] Setting default volume...                     volume=0.20
INFO[0045] Caching disabled.
INFO[0045] Successfully reconnected to the server!
INFO[0048] A user has disconnected or changed channels, updating skip trackers...  user=MumbleDJ
WARN[0057] Sending an error message...                   message=No valid tracks were found with the provided URL(s). user=Perdouille
INFO[0071] Sending a message to channel...               channel=Salon 1
message=<b>Perdouille</b> added <b>1</b> track to the queue: [YOUTUBE VIDEO 2]

*Plays video 1 instead of 2*
---

```
#### Description of your issue:

Hello !

First, thanks for this software. It's very useful, and I'm having fun adding some specific stuff for my own Mumble server :)

I just updated everything to the last release, but I noticed some bugs. I will probably do other bugs report after finding how to reproduce them. Here is how to reproduce one of the bug : 

!add a video (I used Youtube but it probably works with the others as well). Kick the bot.

It will reconnect correctly but wont play anything. !add another video, it will restart the first one

**Comment by matthieugrieger** [comment]
Hi, thanks for the bug report!

This shouldn't be too difficult to fix. I think the most predictable thing to happen in this situation is to have the queue be cleared whenever the bot disconnects (for whatever reason).

I'll push out a fix in a few hours.

**Comment by matthieugrieger** [comment]
Fixed, thanks again!
