### ISSUE TITLE
The audio download for this video failed. <the video> has likely not generated the audio files for this track yet.

### ISSUE THREAD

**Issue by epilimic** [matthieugrieger/mumbledj#167]
#### Before submitting this issue, please acknowledge that you have done the following:
- [x] I've at least skimmed through the [README](https://github.com/matthieugrieger/mumbledj/blob/master/README.md)
- [x] I have checked that I am running the latest version of MumbleDJ (use `mumbledj --version` when starting the bot or use the MumbleDJ version command in Mumble)
- [x] I have [searched through the existing issues](https://github.com/matthieugrieger/mumbledj/issues) to see if my issue has been answered already

---

#### What type of issue is this?
- [ ] Bug report (encountered problems with MumbleDJ)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other:

---

#### Log output of bot with `--debug` flag (likely only for bug reports):

---

#### Description of your issue:

Sometimes when we add songs it won't work. The error message is always the same. What does this mean? 

!add https://www.youtube.com/watch?v=I33u_EHLI3w  
[3:18:18 PM] (Channel) Jukebox: muttlęy has added "'Rocky Balboa' - Theme Song (HD)" to the queue.   
[3:18:20 PM] Jukebox: The audio download for this video failed. 'Rocky Balboa' - Theme Song (HD) has likely not generated the audio files for this track yet. Skipping to the next song!

**Comment by matthieugrieger** [comment]
Are you sure you're using the latest version of MumbleDJ?

**Comment by epilimic** [comment]
I am. I was able to see the issue, youtube-dl needed to be updated. Apologies for not catching that before submitting this here.
