### ISSUE TITLE
Request 2

### ISSUE THREAD

**Issue by MrKrucible** [matthieugrieger/mumbledj#17]
On the topic of requests by [caindrac](https://github.com/matthieugrieger/mumbledj/issues/15), my guys have asked for a simple <code>!help</code> command.

I can see that now the issues section is kinda blowing up XD
Good to see more people getting interested in this project.

**Comment by matthieugrieger** [comment]
Good idea. I'm guessing you're thinking of a help command that displays the available commands and how to use them, sort of like the README?

**Comment by raz0rsdge** [comment]
Oh yeah, that would be fine for the users ;)

**Comment by MrKrucible** [comment]
Went ahead and added this feature myself! First time trying out go code and not too bad...
https://github.com/matthieugrieger/mumbledj/pull/18

**Comment by matthieugrieger** [comment]
Thanks for the PR! It has been merged and tweaked slightly.
