### ISSUE TITLE
Bot crashed after mumble restart

### ISSUE THREAD

**Issue by Axi0m-S** [matthieugrieger/mumbledj#172]
It seems that if the mumble server crash or is restarted, the bot crashes few songs after it has reconnected. Here is what I got as an error

time="2016-08-14T13:29:03+02:00" level=warning msg="Disconnected from server. Retrying connection..." attempts=10 interval_secs=5
panic: runtime error: index out of range

goroutine 78 [running]:
panic(0xa0e8e0, 0xc820010090)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/matthieugrieger/mumbledj/bot.(*Queue).Skip(0xc820128c00)
        /opt/GOSTUFF/src/github.com/matthieugrieger/mumbledj/bot/queue.go:203 +0x4b1
github.com/matthieugrieger/mumbledj/bot.(*Queue).PlayCurrent.func1(0xc820128c00)
        /opt/GOSTUFF/src/github.com/matthieugrieger/mumbledj/bot/queue.go:312 +0x35
created by github.com/matthieugrieger/mumbledj/bot.(*Queue).PlayCurrent
        /opt/GOSTUFF/src/github.com/matthieugrieger/mumbledj/bot/queue.go:313 +0xb2e

I think I can reproduce if necessary

**Comment by Axi0m-S** [comment]
It seems that "!reset" does the same thing. Am I the only one with this problem ?

**Comment by matthieugrieger** [comment]
It's a bug. Thanks for the report!

I'll push out a fix.

**Comment by matthieugrieger** [comment]
@Axi0m-S: It should be fixed now. Let me know if you still experience any issues!

**Comment by Pherr** [comment]
@matthieugrieger I'm still getting this error with !reset and !forceskip on the latest pre-compiled binary.
