### ISSUE TITLE
[error] - certificate signed by unknown authority

### ISSUE THREAD

**Issue by HiveSolution** [matthieugrieger/mumbledj#177]
#### Before submitting this issue, please acknowledge that you have done the following:
- [x] I've at least skimmed through the [README](https://github.com/matthieugrieger/mumbledj/blob/master/README.md)
- [x] I have checked that I am running the latest version of MumbleDJ (use `mumbledj --version` when starting the bot or use the MumbleDJ version command in Mumble)
- [x] I have [searched through the existing issues](https://github.com/matthieugrieger/mumbledj/issues) to see if my issue has been answered already

---

#### What type of issue is this?
- [ ] Bug report (encountered problems with MumbleDJ)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other:

---

#### Log output of bot with `--debug` flag (likely only for bug reports):
```
INFO[0000] Checking for duplicate aliases...
INFO[0000] Performing startup checks...
INFO[0000] Checking for availability of services...      num_services=3
WARN[0000] A startup check discovered an issue. The service will be disabled.  error=No SoundCloud API key has been provided service=SoundCloud
INFO[0000] Checking YouTubeDL installation...
INFO[0000] Checking ffmpeg installation...
INFO[0000] Checking aria2c installation...
WARN[0000] aria2 is not installed or is not discoverable in $PATH. The bot will still partially work, but some services will not work properly.
INFO[0000] Checking openssl installation...
INFO[0000] Attempting connection to server...            address=<removed> port=64738
FATA[0000] An error occurred while connecting to the server.  error=x509: certificate signed by unknown authority
```
---

#### Description of your issue:
When trying to connect to a friends Mumble Server i get the following error:
`error=x509: certificate signed by unknown authority`

So i tried using the `-i` Parameter. No success either.
`error=no certificate: A certificate is required to connect to this server`

**Comment by matthieugrieger** [comment]
Self-signed certificates do not work with MumbleDJ. You'll have to get a trusted cert from LetsEncrypt or a similar service to use your own certificate. Also, this certificate must be the certificate that the server uses.

Does your friend's Mumble server require users to have a certificate to connect? In other words, does his `mumble-server.ini` have `certrequired=false`?

**Comment by HiveSolution** [comment]
Thanks for your help, we set `certrequired=false` and the config of MumbleDj `insecure=true` and it finally worked.

Not really a good way, but for a small private Server with 5 People on it? Not really a big deal.

Again, thanks for the help, we really enjoy having the bot on our server.

**Comment by matthieugrieger** [comment]
Yeah, that should be fine for a small server. Glad it works now! Let me know if you come across any other issues.
