### ISSUE TITLE
Question about server certificates.

### ISSUE THREAD

**Issue by Fyren** [matthieugrieger/mumbledj#179]
#### Before submitting this issue, please acknowledge that you have done the following:
- [x] I've at least skimmed through the [README](https://github.com/matthieugrieger/mumbledj/blob/master/README.md)
- [x] I have checked that I am running the latest version of MumbleDJ (use `mumbledj --version` when starting the bot or use the MumbleDJ version command in Mumble)
- [x] I have [searched through the existing issues](https://github.com/matthieugrieger/mumbledj/issues) to see if my issue has been answered already

---

#### What type of issue is this?
- [ ] Bug report (encountered problems with MumbleDJ)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other:

---

#### Description of your issue:

I've got a question about providing the bot with server certificates and keys.  Is this feature not for SSL pinning?  The bot appears to want the server's _private_ key, which seems crazy.

If I provide only the server's certificate, I get this:
```
FATA[0000] An error occurred while connecting to the server.  error=tls: found a certificate rather than a key in the PEM for the private key
```

If I provide the cert and public key (in the same file), I get this:
```
FATA[0000] An error occurred while connecting to the server.  error=tls: failed to find PEM block with type ending in "PRIVATE KEY" in key input after skipping PEM blocks of the following types: [CERTIFICATE PUBLIC KEY]
```

I am using the autogenerated certs for murmur.  I understand that a self-signed cert isn't trustable in a vacuum, and so why I can't just only set insecure to false and have the bot connect.  But why shouldn't insecure set to false work as long as I also provide either of the certificate or public key?  Or am I misunderstanding the purpose of the --cert/--key options?

**Comment by matthieugrieger** [comment]
Anything related to certificates is handled by the `tls` go package, specifically [`LoadX509KeyPair()`](https://golang.org/pkg/crypto/tls/#LoadX509KeyPair). `LoadX509KeyPair takes a public/private key pair as its input. 

If you use `--insecure` you shouldn't have to provide any cert or key. Is the bot still not able to connect when using `--insecure`? Do you require users who connect to your server to have certificates?

**Comment by Fyren** [comment]
My issue isn't with just getting the bot to connect.  If --cert/--key are supposed to be for SSL pinning, then they don't work.  You can do pinning by only providing the server's cert or key.  Requiring the server's private key for that is aboslutely the wrong thing to do.  So, what are the purpose of --cert/--key?  What is the intended feature?

From the Go docs, what I am probably looking for would be use the tls Dial, then get the ConnectionState from the Conn, then compare the cert provided to the bot with the PeerCertificates.  (Or the public key provided to the bot with the public keys extracted from the PeerCertificates.)

**Comment by matthieugrieger** [comment]
Sorry about the late response, been busy with work.

I think it may be worth opening an issue on the [gumble](https://github.com/layeh/gumble) repo, as I'm simply following the example set there.

Here's an example in a related project where the same method is used: https://github.com/layeh/piepan/blob/master/cmd/piepan/main.go#L62-L72

If you know of a better/more secure way to do this, please feel free to open a PR. To be quite honest with you I'm not an expert on SSL-related things.

**Comment by Fyren** [comment]
It looks like those two parameters are not for pinning but for user auth, since piepan and gumble's sample code don't accept the user's key and cert in p12 format.

For pinning, the general idea would be connect, get the connection state, then from that get the peer certificates and make sure the public key of one of the certs matches a public key for the server that the user provides.  I don't think most users would care for this feature, though.

**Comment by matthieugrieger** [comment]
Yeah, the key and cert are in `pem` format.

You can, however, use the `--p12` commandline argument to supply a `p12` file for authenticating as a registered user.
