### ISSUE TITLE
Skip feature

### ISSUE THREAD

**Issue by azlux** [matthieugrieger/mumbledj#182]
- Feature request (request for a new functionality)

It's not really a new feature, it's exist into the previous version of mumbledj.
You had a function skip who check the submitter and skip the music without wait for the vote, but this don't exist into the current bot. 
That was a line like that :
```
else if dj.queue.CurrentSong().Submitter() == user.Name -> skip
```
It's is possible to reimplement it ?

**Comment by matthieugrieger** [comment]
Yes, this is actually something that was brought up by someone else via email a few days ago. I'm surprised I missed adding this feature back in...

Definitely possible to re-implement this, I will get to it as soon as I can.

**Comment by matthieugrieger** [comment]
The latest release has this feature re-implemented. Sorry about it being missing for so long!
