### ISSUE TITLE
Go panic (unknown edition)

### ISSUE THREAD

**Issue by azlux** [matthieugrieger/mumbledj#184]
Hi,
No idea why I have this bug.
The log can help you to understand : [here the bin](https://azlux.fr.nf/bin/?87ec52f2324b8dba#pWnVT7YrpP6mXdF6eeIo+uPwRbTqNt7V3kF+wSZHJB0=)
Thank

**Comment by matthieugrieger** [comment]
Looks like it might be an issue with gopus.

@bontibon: Does this look like a gopus issue to you?

**Comment by bontibon** [comment]
Website isnt loading. Paste the log in the github issue please.

**Comment by azlux** [comment]
[paste again](https://pastie.crystalyx.net/?66f3ecc7d92d53c7#Vz27SdXMI6OftcK4XnK603nzgR6y5kJkPBiOMZaYzNk=)
The previous one still work.
