### ISSUE TITLE
Make error (again)

### ISSUE THREAD

**Issue by AmalieNot** [matthieugrieger/mumbledj#19]
After cloning and navigating to the directory on my ubuntu server, I get this when I try to make it:

go get -u github.com/layeh/gumble/gumble
# github.com/layeh/gumble/gumble
/root/go/src/github.com/layeh/gumble/gumble/client.go:97: undefined: tls.DialWithDialer
Makefile:4: recipe for target 'mumbledj' failed
make: *** [mumbledj] Error 2

How can I fix this?  Thank you in advance!

**Comment by matthieugrieger** [comment]
What version of Go do you have installed? 1.3 or above is required, and I believe this make error happens when that requirement isn't met.

**Comment by AmalieNot** [comment]
That was it - I was on 1.2.1 due to go being already installed in a directory I didn't check.  I'm on 1.3.2 now and it works!  Thank you!
