### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by caindrac** [matthieugrieger/mumbledj#20]
I am having a problem that start when I updated to the newest mumbleDJ version. When in installed the newest version I updated all the dependency packages. My murmur server runs at 62 kbit/s after this update my bot is only running at about 32 kbit/s and this is making the sound not clear. I don't know if this has something to do with the bot or gumble.

**Comment by matthieugrieger** [comment]
MumbleDJ does not mess with audio bitrate directly, so this is most likely a gumble issue. MumbleDJ changes the audio bitrate dynamically using the [AutoBitrate Event Listener from gumbleutil](https://github.com/layeh/gumble/blob/master/gumbleutil/bitrate.go).

**Comment by matthieugrieger** [comment]
@caindrac: Try pulling the latest change and rebuilding. I made a change that *may* make the audio sound better. Let me know if it makes any difference.

**Comment by matthieugrieger** [comment]
@caindrac: Any updates? Is it working now?

**Comment by caindrac** [comment]
It is working now re-installed it.

**Comment by matthieugrieger** [comment]
Cool!
