### ISSUE TITLE
error youtube

### ISSUE THREAD

**Issue by THEDARKK** [matthieugrieger/mumbledj#21]
Hello, I have this error.
The audio download for this video failed. YouTube has likely not generated the audio files for this video yet.

Best Regards

**Comment by matthieugrieger** [comment]
What is the upload date of the video you are trying to play? This message is displayed when a m4a audio file does not exist for the video. This should only happen between the time the video is uploaded and when the audio files are generated.

**Comment by THEDARKK** [comment]
Example : https://www.youtube.com/watch?v=p9mmhh_wvkA no work

**Comment by matthieugrieger** [comment]
I see. This isn't actually a bug on MumbleDJ's end, but an issue on YouTube's end. A m4a audio file (which is generated for pretty much all videos I have seen) has not been generated for this video, meaning it cannot be played in MumbleDJ, unfortunately.
