### ISSUE TITLE
Admins list not applying

### ISSUE THREAD

**Issue by MrKrucible** [matthieugrieger/mumbledj#22]
Adding new names to the Admins list like ```Admins = "MrKrucible"``` still does not apply access to admin commands.

Though changing my name to Matt enables me to use the admin commands, even if ```Admins = "Matt"``` is not in the mumble.gcfg file.

Running ```sudo nano mumble.gcfg``` so I _know_ the file has been written and double-checked spelling.

**Comment by matthieugrieger** [comment]
Are you editing the `mumbledj.gcfg` file in the directory where you compiled MumbleDJ, or are you editing `~/.mumbledj/mumbledj.gcfg`? The latter is the one you want to edit. This is where MumbleDJ looks for configuration options.

In gcfg, the method for assigning an array of strings to a variable is a bit weird. But it seemed to work with for me when I did it in the way it is explained in the config file.

**Comment by MrKrucible** [comment]
OH! I didn't even know that this folder was being created. I should of paid attention and read the Setup more carefully. _Being tired never helps solve problems._

Thanks again, Matt for developing!

**Comment by matthieugrieger** [comment]
Haha, no problem! :)
