### ISSUE TITLE
AUDIO_FAIL_MSG

### ISSUE THREAD

**Issue by albertwohletz** [matthieugrieger/mumbledj#24]
I had an issue where my distribution of ubuntu having an older version of youtube-dl in apt-get, which causes the AUDIO_FAIL_MSG / "The audio download for this video failed. YouTube has likely not generated the audio files for this video yet." message to appear whenever you try to !add a song.  This is somewhat confusing, as it's really a dependency issue.  

It looks so similar to this issue https://github.com/matthieugrieger/mumbledj/issues/21 that I thought it was actually an issue with youtube, and not with my configuration.  

Not a big issue, I just wanted to mention it.  Thanks for writing this, it works great.

**Comment by matthieugrieger** [comment]
Thanks for pointing this out. I will try to remember to add a note to the setup guide about the installation of the youtube-dl dependency.

The other issue you linked to was actually a slightly different issue. I tested it myself with the most up-to-date youtube-dl and I got the error as well. For that situation I think YouTube just didn't have a m4a file generated for that particular video.

**Comment by matthieugrieger** [comment]
I added a small warning in the setup guide section of the README.
