### ISSUE TITLE
!nextsong not correct when using playlists.

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#26]
If the audio download for this video failed. then !nextsong is never updated.

**Comment by matthieugrieger** [comment]
Thanks for the report! I will look into this as soon as possible.

**Comment by hamilton5** [comment]
Maybe it's when multiple playlists are added, !nextsong is the first song in the nextplaylist ?  Right now I just notice !nextsong not correct alot.

**Comment by matthieugrieger** [comment]
I'll take a look at this. It is possible that the !nextsong command is messed up when multiple playlists are added as I don't think I tested that specific situation.

**Comment by matthieugrieger** [comment]
Looks like I had some stupid code there. Should work fine now. :)

Thanks for the bug report!
