### ISSUE TITLE
Minor: large mixes make queue hung for a while

### ISSUE THREAD

**Issue by raz0rsdge** [matthieugrieger/mumbledj#27]
My friends used to add some mixes to the mumbledj queue, for instance a 237 minutes lasting megamix - I dunno whether it was a joke or serious =)
MumbleDJ then needs a very long time to process this 4h Mix (I asume to render the m4a..) I wonder if there is a way to produce a textmessage if the processing is longer than 30 seconds maybe:
"MumbleDJ is processing an !add request..." or sumthin, because there's only the <b>User has added "XY" to the queue<b> message.

We talked about the way the queue is processed, afaik after playback while movin onto next song in queue the last song is deleted. For future improvement like !random or !repeat[song,playlist] I suggest an internal memory of the !add commands, so maybe that's a way mumbledj can remember the contents of the queue to a certain date. 

Lets say we have added 2 playlists to the queue and after that we have at the end of the playtime some users wish to repeat whole 2 playlists - at the current state thats not possible afaik - but if MumbleDJ has cached the !add requests, it is able to repeat playlists or just internally repeat the cached !add commands...

That all is not important for now, but I'd like to know what other users think about it... heading into DJ capability direction ;-)

Thx again Matt for being so patient with me.

**Comment by matthieugrieger** [comment]
Thanks for the idea! I have actually considered doing something like this, where a value in the config file can be changed to allow caching of downloaded audio files. Doing just that would be fairly easy to implement, but I would like to have some sort of auto-cleanup of old audio files as well.

I think this is a good idea though. I just didn't think anybody would care, or be playing 4 hour mixes with MumbleDJ. ;)

**Comment by matthieugrieger** [comment]
@raz0rsdge: I just thought of another idea to go along with this. What do you think about a !save command? Basically if you issue `!save <youtube_url>` it will permanently save the audio file within `~/.mumbledj/songs/saved`. So if there is a song that is played a lot, it can be kept on hand for the next time it is used.

I will likely implement a way to both save a file permanently and have cached files that delete themselves after a user-defined amount of time. Just thought I would see if this is something that could possibly be used.

**Comment by hamilton5** [comment]
I wondered during play could it also get the nextsong... because of this long delay(hung) between big songs.

**Comment by matthieugrieger** [comment]
@hamilton5: That is something I have wanted to implement but I just haven't gotten around to it. I'll try it out sometime to make sure it doesn't degrade performance.

**Comment by raz0rsdge** [comment]
I think @hamilton5 could be right, maybe its better to define in the configuration how much data is stored on disk and how long it stays there. 

imho, the save command  could be useful to generate some repeatable content? Maybe we have !save<b>d<b> 10 youtube URLs and generated the audio data, we could use a trigger like !repeat to  replay from ~/mumbledj/songs/saved? Let's say if no new URL was added since reaching the end of the queue.

There must be a way to avoid typing !add for same URLs again and again ;)

**Comment by matthieugrieger** [comment]
@raz0rsdge: Alright, I will focus on setting up a caching system with a combined file size limit and file expiration. Both will be able to be tweaked in the config file. I may also add something like the !save command that I mentioned earlier if I get the time.

**Comment by raz0rsdge** [comment]
That sounds great to me - can't wait for the results! 
Thanks and don't loose focus on (MIT?) =)

**Comment by hamilton5** [comment]
I think if you have a !save you need a !showsaved and then maybe a !play x too?? can some of this information be messaged to the user and not public to channel too - !currentsonginfo ;]?? dos protection - what stops a player from spamming !add https://www.youtube.com/watch?v=8qnQz8kxte0 for example?

**Comment by matthieugrieger** [comment]
@hamilton5 That's something I hadn't thought of before. I'll have to look into some spam prevention.

**Comment by raz0rsdge** [comment]
OMG I got rickrolled ;]

**Comment by MrKrucible** [comment]
```!save <yt-link>```
```!list (shows saved yt links)```
```!play <yt-link>```

Maybe add in the config how many songs can be saved, and make ```!save``` an Admin only command by default. Someone spamming ```!save``` wouldn't be too useful; so maybe include some way to prevent duplicates from being added to the saved list?

**Comment by matthieugrieger** [comment]
@MrKrucible: I was planning on making it an admin command by default. I will also make sure to add duplicate checking as well.

I'd like to somehow make it easier to use the `!play` command though. I'm thinking that maybe the user who saves the song can give it an alias like so: `!save <yt-link> <alias>`, and then play it with `!play <alias>`.

**Comment by MrKrucible** [comment]
Huh, special characters should be omitted from alias titles then to prevent any abuse of the aliases.
Specifically only characters from the [basic unicode.](https://en.wikipedia.org/wiki/Basic_Latin_%28Unicode_block%29)

**Comment by matthieugrieger** [comment]
@MrKrucible In what situations would the aliases be able to be abused with Unicode? I may just be missing some obvious examples but I can't think of any.

I'm assuming that most people would be using `!save` as an admin command anyway which would greatly reduce the chance that users will abuse it.

**Comment by matthieugrieger** [comment]
I just added song caching options. I may implement some of the other ideas later, but I think this will at least solve some of the hanging problems.
