### ISSUE TITLE
Makefile errors on armhf

### ISSUE THREAD

**Issue by evanjohnman** [matthieugrieger/mumbledj#28]
I'm attempting to run this off a Raspberry Pi (a small, inexpensive microcomputer) running a arm-specific distro of Wheezy. However, Wheezy doesn't (officially) support Go beyond 1.0.2. 
I attempted to install 1.4.1 from source and simply got a nastier error. (All imports failed)

Would be possible to build MumbleDJ on a different box and copy it over to Raspian? Or would I just have to run it off a different system entirely?

**Comment by evanjohnman** [comment]
My GOPATH and GOROOT are both set to what I assume are the correct places.
(GOROOT to the Go installation, GOPATH to the MumbleDJ files)
Added GOPATH to PATH.

**Comment by raz0rsdge** [comment]
Please paste the output of the build process here, maybe its helpful to get a clue whats going wrong.
Its said that GO1.3 or HIGHER is required (README.md) - so afaik this couldn't be the problem... 

Maybe some off the other requirements or depencies are not met as described here:
https://github.com/matthieugrieger/mumbledj/blob/master/README.md

I'm not a programmer but I am willing to help ;)

**Comment by evanjohnman** [comment]
I've installed, uninstalled, and reinstalled all other prereqs.
Opus
Mercurial
FFMPEG
youtube-dl (Via reccomended tarball)

I clone the latest release, 

Here's the long import error:
root@evanspi:/home/pi/mumbledj# make
go get -u github.com/layeh/gumble/gumble
package github.com/layeh/gumble/gumble
        imports bufio: unrecognized import path "bufio"
package github.com/layeh/gumble/gumble
        imports bytes: unrecognized import path "bytes"
package github.com/layeh/gumble/gumble
        imports crypto/rand: unrecognized import path "crypto/rand"
package github.com/layeh/gumble/gumble
        imports crypto/tls: unrecognized import path "crypto/tls"
package github.com/layeh/gumble/gumble
        imports crypto/x509: unrecognized import path "crypto/x509"
package github.com/layeh/gumble/gumble
        imports encoding: unrecognized import path "encoding"
package github.com/layeh/gumble/gumble
        imports encoding/binary: unrecognized import path "encoding/binary"
package github.com/layeh/gumble/gumble
        imports encoding/json: unrecognized import path "encoding/json"
package github.com/layeh/gumble/gumble
        imports errors: unrecognized import path "errors"
package github.com/layeh/gumble/gumble
        imports fmt: unrecognized import path "fmt"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports io: unrecognized import path "io"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports log: unrecognized import path "log"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports math: unrecognized import path "math"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports os: unrecognized import path "os"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports reflect: unrecognized import path "reflect"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports runtime: unrecognized import path "runtime"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports sort: unrecognized import path "sort"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports strconv: unrecognized import path "strconv"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports strings: unrecognized import path "strings"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports sync: unrecognized import path "sync"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports unicode/utf8: unrecognized import path "unicode/utf8"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports unsafe: unrecognized import path "unsafe"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports github.com/layeh/gopus
        imports github.com/layeh/gumble/gumble/MumbleProto
        imports github.com/layeh/gumble/gumble/varint
        imports net: unrecognized import path "net"
package github.com/layeh/gumble/gumble
        imports github.com/golang/protobuf/proto
        imports github.com/layeh/gopus
        imports github.com/layeh/gumble/gumble/MumbleProto
        imports github.com/layeh/gumble/gumble/varint
        imports time: unrecognized import path "time"
Makefile:4: recipe for target 'mumbledj' failed
make: *** [mumbledj] Error 1

The short one:
CNR
But mentioned not being able to import files from encoding, because no source files exist in that folder. I believe this was gumble, rather than mumbledj, but I've been unable to reproduce it.

I'm not much of a programmer, either. But I want a way of playing music in Mumble, so I'm trying.

**Comment by matthieugrieger** [comment]
@evanjohnman:
A few things:

**1)** Your `$GOPATH` variable is not set correctly, which may be causing some of your errors. Your `$GOPATH` declaration should look like this: `export GOPATH=$GOROOT/bin`, and `$GOPATH` should be appended to your `$PATH` like so: `export PATH=$PATH:$GOPATH`. This isn't the only way to set this up, but it is how I did it.

**2)** Your errors when compiling Go 1.4.1 from source may be related to your path issues, but as long as you get a Go 1.3+ installation working compilation *should* work.

**3)** Theoretically, it is *probably* possible to compile MumbleDJ on another machine and transfer it to your Pi, but I have not tried it. Go binaries are [statically linked](http://golang.org/doc/faq#Why_is_my_trivial_program_such_a_large_binary), meaning it should contain all the necessary code to run.

**4)** To be completely honest with you, you may struggle with getting a reliable experience running MumbleDJ on a Raspberry Pi. In order for the audio to play over Mumble, MumbleDJ transcodes the audio through `gumble` which is a fairly CPU-intensive task. The Raspberry Pi, while great (I own two!) doesn't really possess the processing power. The creator of `gumble` answered a similar question here: https://github.com/layeh/piepan/issues/13#issuecomment-67711299.

I hope this helps! Let me know if there are any other questions.

**Comment by evanjohnman** [comment]
Alright. I'll just run it off a Debian VM instead. (I suppose it _would_ take more CPU power than the Pi can output.) 

Thanks for your help!
