### ISSUE TITLE
Client crashing after a few hours of play time.

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#31]
What kind of !uptime and !totalplayed songs do people get? I'm crashing after about 2 hours of playing. All I have is output when it panics hope it is helpful. please advise.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45eb44]

goroutine 80 [running]:
runtime.panic(0x783fc0, 0xbfd813)
        /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/layeh/gumble/gumble.(*User).Send(0x0, 0x8a94d0, 0x6e)
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/user.go:266 +0x104
main.(*SongQueue).PrepareAndPlayNextItem(0xc20803c0a0)
        /home/user/gobuild/src/github.com/matthieugrieger/mumbledj/songqueue.go:144 +0x3c5
main.(*SongQueue).OnItemFinished(0xc20803c0a0)
        /home/user/gobuild/src/github.com/matthieugrieger/mumbledj/songqueue.go:109 +0x463
main.*SongQueue.OnItemFinished·fm()
        /home/user/gobuild/src/github.com/matthieugrieger/mumbledj/main.go:54 +0x26
github.com/layeh/gumble/gumble_ffmpeg.func·001()
        /home/user/gobuild/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:99 +0xa5
github.com/layeh/gumble/gumble_ffmpeg.(*Stream).sourceRoutine(0xc2080cc360)
        /home/user/gobuild/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:112 +0x2b2
created by github.com/layeh/gumble/gumble_ffmpeg.(*Stream).Play
        /home/user/gobuild/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:60 +0x31e

goroutine 16 [chan receive, 96 minutes]:
main.main()
        /home/user/gobuild/src/github.com/matthieugrieger/mumbledj/main.go:147 +0x4ef

goroutine 19 [finalizer wait, 4 minutes]:
runtime.park(0x41fa40, 0xc15ec0, 0xc023a9)
        /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xc15ec0, 0xc023a9)
        /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall, 96 minutes]:
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7f3e194b4970, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208024300, 0x72, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208024300, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc2080242a0, 0xc20803ac00, 0x400, 0x400, 0x0, 0x7f3e194b3418, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc208038028, 0xc20803ac00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/net.go:122 +0xe7
crypto/tls.(*block).readFromUntil(0xc208021620, 0x7f3e194b4a48, 0xc208038028, 0x5, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:451 +0xd9
crypto/tls.(*Conn).readRecord(0xc208074580, 0x17, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:536 +0x1ff
crypto/tls.(*Conn).Read(0xc208074580, 0xc20823d770, 0x2, 0x8, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:901 +0x16a
io.ReadAtLeast(0x7f3e194b4f08, 0xc208074580, 0xc20823d770, 0x2, 0x8, 0x2, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/io/io.go:289 +0xf7
io.ReadFull(0x7f3e194b4f08, 0xc208074580, 0xc20823d770, 0x2, 0x8, 0x4, 0x0, 0x0)
        /usr/lib/go/src/pkg/io/io.go:307 +0x71
encoding/binary.Read(0x7f3e194b4f08, 0xc208074580, 0x7f3e194b4e20, 0x0, 0x6b63c0, 0xc20823d768, 0x0, 0x0)
        /usr/lib/go/src/pkg/encoding/binary/binary.go:147 +0x12b
github.com/layeh/gumble/gumble.(*Client).readRoutine(0xc2080f0000)
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/client.go:190 +0x23d
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/client.go:111 +0x344

goroutine 21 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0xc2080f0000)
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/client.go:166 +0x291
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/client.go:112 +0x35f
[1]+  Exit 2                  ./mumbledj -server=hostname.net -port=64738 -username=iPlayMuzak -channel=Surfin

*********************************

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45eb44]

goroutine 77 [running]:
runtime.panic(0x783fc0, 0xbfd813)
        /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/layeh/gumble/gumble.(*User).Send(0x0, 0x8a94d0, 0x6e)
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/user.go:266 +0x104
main.(*SongQueue).PrepareAndPlayNextItem(0xc20803c0a0)
        /home/user/gobuild/src/github.com/matthieugrieger/mumbledj/songqueue.go:144 +0x3c5
main.(*SongQueue).OnItemFinished(0xc20803c0a0)
        /home/user/gobuild/src/github.com/matthieugrieger/mumbledj/songqueue.go:109 +0x463
main.*SongQueue.OnItemFinishedÂ·fm()
        /home/user/gobuild/src/github.com/matthieugrieger/mumbledj/main.go:54 +0x26
github.com/layeh/gumble/gumble_ffmpeg.funcÂ·001()
        /home/user/gobuild/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:99 +0xa5
github.com/layeh/gumble/gumble_ffmpeg.(*Stream).sourceRoutine(0xc20810acc0)
        /home/user/gobuild/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:112 +0x2b2
created by github.com/layeh/gumble/gumble_ffmpeg.(*Stream).Play
        /home/user/gobuild/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:60 +0x31e

goroutine 16 [chan receive, 244 minutes]:
main.main()
        /home/user/gobuild/src/github.com/matthieugrieger/mumbledj/main.go:147 +0x4ef

goroutine 19 [finalizer wait, 4 minutes]:
runtime.park(0x41fa40, 0xc15ec0, 0xc023a9)
        /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xc15ec0, 0xc023a9)
        /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall, 244 minutes]:
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7fd1e87dda58, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208024300, 0x72, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208024300, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc2080242a0, 0xc20803a800, 0x400, 0x400, 0x0, 0x7fd1e87dc418, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc208038028, 0xc20803a800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/net.go:122 +0xe7
crypto/tls.(*block).readFromUntil(0xc2080215f0, 0x7fd1e87ddb30, 0xc208038028, 0x5, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:451 +0xd9
crypto/tls.(*Conn).readRecord(0xc2080be000, 0x17, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:536 +0x1ff
crypto/tls.(*Conn).Read(0xc2080be000, 0xc20810d730, 0x2, 0x8, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:901 +0x16a
io.ReadAtLeast(0x7fd1e87ddff0, 0xc2080be000, 0xc20810d730, 0x2, 0x8, 0x2, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/io/io.go:289 +0xf7
io.ReadFull(0x7fd1e87ddff0, 0xc2080be000, 0xc20810d730, 0x2, 0x8, 0x4, 0x0, 0x0)
        /usr/lib/go/src/pkg/io/io.go:307 +0x71
encoding/binary.Read(0x7fd1e87ddff0, 0xc2080be000, 0x7fd1e87ddf08, 0x0, 0x6b63c0, 0xc20810d728, 0x0, 0x0)
        /usr/lib/go/src/pkg/encoding/binary/binary.go:147 +0x12b
github.com/layeh/gumble/gumble.(*Client).readRoutine(0xc2080f0000)
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/client.go:190 +0x23d
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/client.go:111 +0x344

goroutine 21 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0xc2080f0000)
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/client.go:166 +0x291
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/user/gobuild/src/github.com/layeh/gumble/gumble/client.go:112 +0x35f

**Comment by matthieugrieger** [comment]
Currently my instance of MumbleDJ has been running for about 5 days straight now. In the past I have had it running for weeks at a time without crashing.

When you say it crashes after 2 hours of playing, is this one song? Or is it multiple songs?

**Comment by bontibon** [comment]
@matthieugrieger The bug appears to be right [here](https://github.com/matthieugrieger/mumbledj/blob/master/songqueue.go#L143); `user` might be nil if the song submitter has disconnected or changed channels.

**Comment by matthieugrieger** [comment]
@bontibon: Good catch, thanks. I will make sure to fix that as soon as
possible.

**Comment by hamilton5** [comment]
cheers!
