### ISSUE TITLE
!command bugs

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#32]
! is the same as !skipplaylist - I don't think it should do anything.. it's not a command just a character.

when using !add, a newline after the youtube url will 'added "" to the queue.' and break it. A !reset after this causes crash.

**Comment by matthieugrieger** [comment]
Thanks for the bug reports. Can you show me a chat log of your '!' issue? I've never experienced it before.

**Comment by matthieugrieger** [comment]
@hamilton5: Ignore my last message. I had the same problem with "!" being recognized as "!skipplaylist". I don't know why that was happening, but it should be fixed in a commit that is coming up soon.

I'm working on fixing the other bugs at the moment.

**Comment by matthieugrieger** [comment]
All the bugs from this issue should be fixed. Thanks for the report! You helped me squash quite a few bugs.

**Comment by hamilton5** [comment]
wont build:

./commands.go:273: cannot call non-function dj.audioStream.Volume (type float32)
./commands.go:278: dj.audioStream.SetVolume undefined (type *gumble_ffmpeg.Stream has no field or method SetVolume)
./commands.go:279: cannot call non-function dj.audioStream.Volume (type float32)
./main.go:54: dj.audioStream.Done undefined (type *gumble_ffmpeg.Stream has no field or method Done)
./main.go:55: dj.audioStream.SetVolume undefined (type *gumble_ffmpeg.Stream has no field or method SetVolume)
