### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#33]
1) be able to set a comment on bot - ie 'I'm just a bot - type !help in channel'

2) Add some way to tell if the !currentsong is from a playlist

**Comment by matthieugrieger** [comment]
Good ideas! Both should be pretty easy to implement. I will add them in as soon as I can.

**Comment by hamilton5** [comment]
only admins see the admin commands when typing !help .

**Comment by matthieugrieger** [comment]
@hamilton5: That is ideally how it will work in the future, just have to implement it.

**Comment by hamilton5** [comment]
A commands to return mumbledj and youtube-dl versions.

external way to !add (ie command line, cron) ?
