### ISSUE TITLE
!move does not work with sub channels.

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#34]
Works fine for channels after root (case sensitive is annoying)
any channel deeper will not work ie game1 or subchan1

root
-AFK
-Games
--game1
--game2
-Notgamming
--subchan1
--subchan2

**Comment by matthieugrieger** [comment]
I'm not sure if there is a nice way to handle the case sensitivity issue. I'll look into it, but no guarantees that there will be a "fix."

The subchannels issue is something that has been on the list for awhile to fix, just need to get around to it (as you can probably see, there are a lot of other issues going on at the moment). It would probably be possible, but may require a syntax where the subchannels are listed after their parent channels like so: `!move Games/game1`.

**Comment by hamilton5** [comment]
I was not sure if it was known. I really don't think a !move is necessary even. Starting up could be the channel ID for all I care.

**Comment by matthieugrieger** [comment]
> Starting up could be the channel ID for all I care.

What do you mean?

**Comment by hamilton5** [comment]
Some ICE scripts I've used in the past would use channel ID. Root channel being '0' next created channel would be ID 1, etc etc. If you 'edit' channel the ID is next to the name in mumble client.

**Comment by matthieugrieger** [comment]
Ah, I get it now.
