### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by raz0rsdge** [matthieugrieger/mumbledj#35]
goop go build .

./commands.go:278: cannot assign to dj.audioStream.Volume
./commands.go:278: cannot use newVolume (type float32) as type func() float32 in assignment
./main.go:54: cannot assign to dj.audioStream.Volume
./main.go:54: cannot use dj.conf.Volume.DefaultVolume (type float32) as type func() float32 in assignment
./song.go:88: too many arguments in call to dj.audioStream.Play
goop: Command failed with exit status 2
make: *** [mumbledj] Error 2

I'd like to point out that MumbleDJ should be installable by a normal user - because we have a lot of multiuser linux environments out there and it's imho not necessary to use a root account...
In the past I simply did this by changing the cp command line in the Makefile:
<b> cp -f mumbledj ~/bin/mumbledj </b>

If I try to build goop separately  as user, I get lots of errors... my GOPATH var seems to be not used anymore... however I can build the goop binary but then I get stuck on <b> goop go build . </b>

**Comment by matthieugrieger** [comment]
I believe this is a weird bug that occurs when you already have Go dependencies installed before using `goop`. What fixed it for me was deleting `.vendor` and `Goopfile.lock` and re-running `make`.

**Comment by raz0rsdge** [comment]
Okay cleaning out did the trick..was able to build with goop now, thanks for the fast reply ;)

**Comment by matthieugrieger** [comment]
Great! Glad it worked. :)

**Comment by raz0rsdge** [comment]
To be honest, I'm not sure if this is a serious problem since I built many depencies with toast:

<b>
# github.com/timshannon/go-openal/openal
In file included from openal/alcCore.go:24:
local.h:5:18: error: AL/al.h: No such file or directory
local.h:6:19: error: AL/alc.h: No such file or directory
</b>

but the build went successfully through...

**Comment by matthieugrieger** [comment]
If the build went through successfully, I wouldn't worry about it.

**Comment by minjun-jeong** [comment]
Did you installed openal-soft and openal-soft-devel ?

**Comment by raz0rsdge** [comment]
jepp.
