### ISSUE TITLE
Certificate support

### ISSUE THREAD

**Issue by mkody** [matthieugrieger/mumbledj#36]
Can you add support to use PEM keys to the bot for authenticating to the server? 
He can't be registered and we can't add him different permissions for some channels with LCAs.

But thanks for this project, it works really fine and it's useful :+1:

**Comment by matthieugrieger** [comment]
I just tested this and it seems to work fine. Let me know if there are any issues!

You may already know this, but just for future reference: if you have your certificate in `.p12` format, it will have to be converted to `.pem` format using the commands described here: http://stackoverflow.com/a/15144560.

**Comment by raz0rsdge** [comment]
It took 15 minutes for me to realize that this only works without passphrase on the private key, so the steps maybe be interesting for others too:

1. Generate private key: <b>$openssl genrsa -des3 -out 'mumbleDJ-Key.pem' 2048 </b>
2. Generate CSR: <b>$openssl req -new -key 'mumbleDJ-Key.pem' -out mumbleDJ.csr </b>
3. Generate self-signed Cert from CSR: <b>$openssl x509 -req -days 365 -in mumbleDJ.csr -signkey 'mumbleDJ-Key.pem' -out 'mumbleDJ-Cert.pem' </b>
4. Remove passphrase from key: <b>$openssl rsa -in 'mumbleDJ-Key.pem' -out 'mumbleDJ-Key.pem' </b>

Source: https://softwareinabottle.wordpress.com/2011/12/18/creating-self-signed-certificates-on-ubuntu-server/

**Comment by mkody** [comment]
@raz0rsdge My steps were
1. Create a new certificat within Mumble and I've named it `mumbledj.p12`
2. Send the p12 file to the server
3. What @matthieugrieger linked: 
```
openssl pkcs12 -in mumbledj.p12 -out mumbledj.crt.pem -clcerts -nokeys
openssl pkcs12 -in mumbledj.p12 -out mumbledj.key.pem -nocerts -nodes
```

**Comment by matthieugrieger** [comment]
@mkody: Did that method work for you? I didn't actually try it myself.

**Comment by mkody** [comment]
@matthieugrieger: Yes, it did work.
