### ISSUE TITLE
Posting binary image data in chat causes crash

### ISSUE THREAD

**Issue by Nariaftw** [matthieugrieger/mumbledj#37]
Easily reproducible, pasting binary image data to chat in a channel where the bot resides seems to make it crash. That is to say, not a link to an image, but the actual image itself, to make it show inline.

Steps to reproduce:
Find any random image in your browser, "Copy Image" from context menu.
Right click on channel name in mumble, send message, paste it in the contents
Send it.

Poof, crash.

If this is something isolated to just me and you can't reproduce it, I can get a log soon when everyone's done using mumble for the day.

**Comment by matthieugrieger** [comment]
Thanks for the bug report! I just tried this on my own server and it does the same thing for me. I'm pretty sure I know what the issue is, I will get it fixed as soon as I can.

What's weird is that it doesn't crash when in the root channel for me... only if it is in a subchannel.

**Comment by Nariaftw** [comment]
Huh, that is odd. It's always been sat in a sub-channel for me, so I hadn't noticed that.

Either way, thanks for the quick response and support such an awesome program! I just started using it, and everyone loves it. I had a couple of feature ideas to throw at you, I'll open an separate item in a little bit.

**Comment by mkody** [comment]
I can confirm that we're having the same bug on our server, and it crash on the root channel too.

**Comment by matthieugrieger** [comment]
Interesting. No worries though. I think I know the fix, I just need to get
out of class to fix it. :)

**Comment by matthieugrieger** [comment]
This should fix it. Let me know if there are any other issues!
