### ISSUE TITLE
Feature Request: Radio/Shuffle mode

### ISSUE THREAD

**Issue by Nariaftw** [matthieugrieger/mumbledj#39]
Having just started using mumbledj, I love it, it does exactly what I was looking for, but when using it a few small things came to mind that would be great to see.

Namely, a shuffle mode. We get pretty excited about adding songs to the playlist, and, often it occurs that any one song you add will not be playing for at least an hour, which is fine, but sometimes it would be nice to mix it up. Just having a !suffle or !shuffleon/!shuffleoff command would be awesome and improve our experience a lot.

Now, on a similar note, I had another idea that involved sort of a fall back playlist, something to play when nothing else is selected. This could be stored in a flat text file with youtube IDs even. User submitted songs would always take precedence, but when it new there was a break in the playlist coming up it would fallback to a predefined list (perhaps added to with commands? !radioadd !radiolist !radioremove.) This mode would always be on shuffle to keep it a bit dynamic, if people really want for some niche use, that could be turned off in settings.

The default mode of it would be interrupted as soon as anyone gives it something to play, and start as soon as it has nothing to play. Perhaps stopping if the channel is empty after a few minutes.

It would be cool if this was toggleable directly as well, but that might just be fluff. This would allow me to say !radioon, and force it to that mode.

Just some thoughts, I absolutely love it as is, but these thigns crossed my mind and thoguht I would share them.

**Comment by matthieugrieger** [comment]
Good ideas!

The shuffle mode is cool, but due to the nature of the data structure I use to represent the queue it wouldn't be (easily) possible to make it so that the queue is always shuffled. Probably the more realistic approach would be to add a `!shuffle` command that shuffles the items that are already in the queue (meaning that any songs added after `!shuffle` would not be shuffled until the command is used again).

The radio mode is also another good idea. Once the shuffle mode is implemented this would be fairly easy to implement, and I may be able to incorporate it with another idea I have been considering (allowing admins to save songs permanently).

**Comment by hamilton5** [comment]
The queue always being shuffled just does not make any sense. !shuffle would work well with playlists..

**Comment by Nariaftw** [comment]
Don't believe anyone said it should always be shuffled. The always comment was for the "radiomode" idea I had outlined.

**Comment by hamilton5** [comment]
!repeat ? when turned on the current queue is looped !add is blocked until repeat is turned off..

**Comment by raz0rsdge** [comment]
that makes sense to me...

**Comment by tcaruth** [comment]
just wanted to throw out there, i would use a radio mode for sure.

currently my users just have full youtube playlists and add 25 at a time, but eventually (inevitably while mid-game) the playlist will end. i'm not familiar enough with go to be of any assistance however :anguished:

**Comment by GabrielPlassard** [comment]
Hi, first, thanks for your awesome work!

I tried to implement a pretty simple mechanism for shuffling but I'm pretty new to go so any comment would be welcome 03a51ed3b6d8afcf5c346f63557aba82866d9938

**Comment by matthieugrieger** [comment]
@GabrielPlassard: Thanks for doing this! I left a comment on the commit. Set up a PR and I'll test & merge it!

**Comment by GabrielPlassard** [comment]
Actually, I used it a bit and I think @Nariaftw idea with !shuffleon and !shuffleoff makes more sense (at least for my use case). So I'm gonna have a look and try to implement it.
Do you prefer 2 separates PRs or only 1 when I'm ready?

**Comment by matthieugrieger** [comment]
@GabrielPlassard I think one PR would be fine. Are you keeping the !shuffle command as well? I think having both options would be cool.

**Comment by GabrielPlassard** [comment]
As long as you think there is a use case for it, I don't see any reason to remove it :)

**Comment by matthieugrieger** [comment]
@GabrielPlassard Keep it then. I know that the people on my server would probably use it!

**Comment by matthieugrieger** [comment]
Closing this issue as shuffle has been implemented. I don't foresee implementing a radio mode any time in the near future.
