### ISSUE TITLE
Auto-reconnect Feature?

### ISSUE THREAD

**Issue by MrKrucible** [matthieugrieger/mumbledj#40]
At times some connection gets broken between either my Mumble server, or the VPS I put MumbleDJ on. Can an auto-reconnect feature be added so I don't have to restart MumbleDJ everytime the connection goes down?

**Comment by matthieugrieger** [comment]
That would be a nice thing to have. I'll put it on the to-do list.

**Comment by hamilton5** [comment]
kicked was not mentioned, hope it was implied.

**Comment by matthieugrieger** [comment]
@hamilton5: Sorry, what do you mean by kicked?

**Comment by MrKrucible** [comment]
I think he means when the MumbleDJ is kicked from the server, then MumbleDJ will try reconnecting.

**Comment by matthieugrieger** [comment]
@MrKrucible: Got it. I'm not sure if MumbleDJ should automatically reconnect upon kick though. It has always annoyed me when users are able to automatically rejoin the server once kicked.

**Comment by hamilton5** [comment]
I can see your point here, but if admin can kick, he can also ban. how about this solution; if the bot is kicked it comes back to root chan or its -channel that was set at cmd line?
