### ISSUE TITLE
goop

### ISSUE THREAD

**Issue by THEDARKK** [matthieugrieger/mumbledj#44]
Hello, I have a problem:

go get github.com/nitrous-io/goop
rm -rf Goopfile.lock
goop install
make: goop: Command not found
make: *** [mumbledj] Error 127

How to solve it?
Best Regards

**Comment by matthieugrieger** [comment]
Your `$PATH` variable isn't configured correctly. Make sure that you append the bin directory within your go installation to `$PATH`.

If you already specified `$GOROOT`, you can do it like this: `export PATH=`$PATH:$GOROOT/bin`.

Hope this helps!
