### ISSUE TITLE
Can't download audio files whose Youtube ID starts with a dash "-"

### ISSUE THREAD

**Issue by y7x** [matthieugrieger/mumbledj#46]
Hi,

When I `!add https://www.youtube.com/watch?v=-w-58hQ9dLk`, I get the "The audio download for this video failed. YouTube has likely not generated the audio files for this video yet. Skipping to the next song!" error message.

The problem seems to be that youtube-dl doesn't recognise video IDs that start with a `-`.
`youtube-dl -w-58hQ9dLk` doesn't work because it confuses the ID with a command line option.
The audio files definitely exist on youtube.

`youtube-dl "ytsearch:'-w-58hQ9dLk'"` doesn't find any results either, so it looks like youtube-dl can't handle it when we only give it a video ID which starts with a `-`.

I worked around it for now by changing line 83 in song.go from
```cmd := exec.Command("youtube-dl", "--output", fmt.Sprintf(`~/.mumbledj/songs/%s.m4a`, s.youtubeId), "--format", "m4a", s.youtubeId)```
to
```cmd := exec.Command("youtube-dl", "--output", fmt.Sprintf(`~/.mumbledj/songs/%s.m4a`, s.youtubeId), "--format", "m4a", fmt.Sprintf(`https://www.youtube.com/watch?v=%s`, s.youtubeId))```

It works of course if you do `youtube-dl -- -w-58hQ9dLk` or use the whole URL for example, but I don't think you or the youtube-dl devs want to have to handle such cases manually (if possible).

Thought I'd let you know of this. Do you think the youtube-dl devs would like to know about this issue or am I missing some obvious solution to this problem?

**Comment by matthieugrieger** [comment]
Ooh, good find! What happens if you just use the existing command and put
quotes around the ID?

**Comment by y7x** [comment]
Then it's just `youtube-dl "-w-58hQ9dLk"`
and produces the same error output:
```
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: you must provide at least one URL
```
still recognised as command line option "w-58hQ9dLk" which youtube-dl obviously doesn't have.

**Comment by matthieugrieger** [comment]
Huh, that's strange. I don't think that's supposed to happen. Maybe submit
an issue for youtube-dl?

**Comment by y7x** [comment]
I'll do that then.

**Comment by y7x** [comment]
Funny thing:

I found ### How do I download a video starting with a `-` ? in their FAQ (https://github.com/rg3/youtube-dl#how-do-i-download-a-video-starting-with-a---)
and it says this:

Either prepend `http://www.youtube.com/watch?v=` or separate the ID from the options with `--`:

    youtube-dl -- -wNyEUrxzFU
    youtube-dl "http://www.youtube.com/watch?v=-wNyEUrxzFU"

I think I'll ask them in the IRC if they really don't see a different solution.

**Comment by bontibon** [comment]
This is simply standard practice on how command line flag are parsed; I think youtube-dl does the right thing here.

MumbleDJ can be easily modified so all video IDs are accepted:

    cmd := exec.Command("youtube-dl", "--output", fmt.Sprintf(`~/.mumbledj/songs/%s.m4a`, s.youtubeId), "--format", "m4a", "--", s.youtubeId)

**Comment by matthieugrieger** [comment]
@bontibon: I was going to do exactly that. Just haven't gotten to it yet. :)
