### ISSUE TITLE
Plans For SoundCloud

### ISSUE THREAD

**Issue by MrKrucible** [matthieugrieger/mumbledj#47]
Does it look like SoundCloud could be implemented as the next big update for MumbleDJ?

**Comment by matthieugrieger** [comment]
Yeah, that would be a good option. `youtube-dl` already supports downloading audio from SoundCloud, so it would be fairly easy to implement.

**Comment by raz0rsdge** [comment]
wow that soundz cool to me ;)

**Comment by MrKrucible** [comment]
bump

**Comment by MichaelOultram** [comment]
I currently have SoundCloud working with mumbledj in my own fork, and I was planning on making a pull request at some point (code needs cleaning up a bit). However, @matthieugrieger has started a refactor off this repository, and so I thought it would be best to hold off on merging.

**Comment by matthieugrieger** [comment]
This is something that I have still been planning on adding. I just haven't had much time/motivation lately to work on it.

@MichaelOultram, I'd be fine with merging! I'm starting university again soon so it might be awhile before I can get to the refactor.

**Comment by MrKrucible** [comment]
@MichaelOultram How soon could we get a merge going?

**Comment by MichaelOultram** [comment]
@MrKrucible That long :stuck_out_tongue:

**Comment by matthieugrieger** [comment]
Closed as SoundCloud is now supported thanks to @MichaelOultram. :)
