### ISSUE TITLE
MumbleDJ: The audio download for this video failed. YouTube has likely not generated the audio files for this video yet. Skipping to the next song!

### ISSUE THREAD

**Issue by jonybravo30** [matthieugrieger/mumbledj#48]
Hello !

I am migrating from piepan (with mumble dj) to this great bot, but i cant play videos when i chat (i am admin in mumbledjconfig):
!add https://www.youtube.com/watch?v=cmXDqH26EMo
Message in mumble client:
jonybravo30 has added "Killzone: Shadow Fall - Review" to the queue. 
[23:13:49] MumbleDJ: The audio download for this video failed. YouTube has likely not generated the audio files for this video yet. Skipping to the next song!
That happens with all youtube videos.

>my execution:
ubuntu@ip:~/mumbledj-2.6.5$ ./mumbledj-2.6.5 -server=localhost -port=64738 -username=MumbleDJ -password="" -channel="ASD" -cert="" -key="" -insecure
Configuration successfully loaded!
(Nothing more)

¿What could It to be happening?Thanks in advance. 

Fantastic tool, its awesome ^_^

**Comment by jonybravo30** [comment]
some debug opts in configuration?

**Comment by mkBlaze** [comment]
Make sure youtube-dl is installed and working properly.

**Comment by matthieugrieger** [comment]
@jonybravo30: I would suggest what @mkBlaze said.

**Comment by jonybravo30** [comment]
Already installed

ubuntu@ip$ dpkg -l | grep youtube
ii  youtube-dl                       2014.02.17-1                          all          downloader of videos from YouTube and other sites

Any ideas?

**Comment by jonybravo30** [comment]
execution test:
ubuntu@ip:~$youtube-dl https://www.youtube.com/watch?v=cmXDqH26EMo
[youtube] Setting language
[youtube] cmXDqH26EMo: Downloading webpage
[youtube] cmXDqH26EMo: Downloading video info webpage
[youtube] cmXDqH26EMo: Extracting video information
[download] Destination: Killzone - Shadow Fall - Review-cmXDqH26EMo.mp4
[download] 100% of 157.29MiB in 00:03
ubuntu@ip:~$

**Comment by matthieugrieger** [comment]
@jonybravo30: Weird.. I'll look at it later but it will be a few days. Currently studying for finals at university.

**Comment by joncolas** [comment]
@matthieugrieger: Great, thanks!!, Good luck with exams.

**Comment by jonybravo30** [comment]
@matthieugrieger: Great, thanks!!, Good luck with exams.

**Comment by matthieugrieger** [comment]
@jonybravo30:
1) Do you have `ffmpeg` installed?
2) If so, while you attempt to play a song, look at the `~/.mumbledj/songs` directory. Do you see files popping up in there?

**Comment by jonybravo30** [comment]
yes, it is installed, 
ubuntu@ip:~$ ffmpeg
ffmpeg version 2.5.4 Copyright (c) 2000-2015 the FFmpeg developers
  built on Feb 15 2015 21:42:49 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libpulse --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
__________________________________________________________________________

ubuntu@ip$ dpkg -l | grep ffmpeg
ii  ffmpeg                           7:2.5.4~trusty1                       amd64        Multimedia player, server, encoder and transcoder

____________________________________________________________________________
I executed in server:
ubuntu@ip:~/$ watch -n 1 'ls -larth ~/.mumbledj/songs'
____________________________________________________________________________
then in mumble client chatbox i put:
!add https://www.youtube.com/watch?v=cmXDqH26EMo

Nothing appears in songs folder(permissions are ok).

Thanks Mathieu!!

**Comment by matthieugrieger** [comment]
Hmm.. Something must not be configured correctly then, since the songs are not appearing in the songs folder.

What happens if you run the following command?
`youtube-dl --output ~/.mumbledj/songs/test.m4a --format m4a --cmXDqH26EMo`

**Comment by jonybravo30** [comment]
ubuntu@ip:~$ youtube-dl --output ~/.mumbledj/songs/test.m4a -f m4a --cmXDqH26EMo
Usage: youtube-dl [options] url [url...]
youtube-dl: error: no such option: --cmXDqH26EMo

I tried, (with no -- in video yt query)
ubuntu@ip:~$ youtube-dl --output ~/.mumbledj/songs/test.m4a -f m4a cmXDqH26EMo
[youtube] Setting language
[youtube] cmXDqH26EMo: Downloading webpage
[youtube] cmXDqH26EMo: Downloading video info webpage
[youtube] cmXDqH26EMo: Extracting video information
ERROR: requested format not available

and then again with mp4 format:
ubuntu@ip:~$ youtube-dl --output ~/.mumbledj/songs/test.mp4 -f mp4 cmXDqH26EMo
[youtube] Setting language
[youtube] cmXDqH26EMo: Downloading webpage
[youtube] cmXDqH26EMo: Downloading video info webpage
[youtube] cmXDqH26EMo: Extracting video information
[download] Destination: /home/ubuntu/.mumbledj/songs/test.mp4
[download] 100% of 157.29MiB in 00:04

list of songs dir:
ubuntu@ip:~$ ls ~/.mumbledj/songs/
test.mp4

So i thought that version was problem then upgrade youtube-dl (sudo pip install --upgrade youtube_dl) and it works!!

Thanks for support Matthieu, +1!

**Comment by matthieugrieger** [comment]
Awesome, glad that fixed it! I had a hunch that `youtube-dl` was out of date.
