### ISSUE TITLE
Unable to make

### ISSUE THREAD

**Issue by TesoMayn** [matthieugrieger/mumbledj#51]
```shell
go get github.com/nitrous-io/goop
package code.google.com/p/go.tools/go/vcs: Get https://code.google.com/p/go/source/checkout?repo=tools: x509: failed to load system roots and no roots provided
make: *** [mumbledj] Error 1
```

Not sure what I did wrong

**Comment by matthieugrieger** [comment]
How did you install `go`? Did you build from source, or install it from a distro repository?

Also, make sure that you have the `ca-certificates` package for your distro installed.

**Comment by TesoMayn** [comment]
I installed via ```yum install golang```

and yes, I have ```ca-certificates``` installed

**Comment by TesoMayn** [comment]
I reinstalled ```ca-certificates```

now I get

```bash
# make
go get github.com/nitrous-io/goop
rm -rf Goopfile.lock
goop install
make: goop: Command not found
make: *** [mumbledj] Error 127

```

**Comment by matthieugrieger** [comment]
Cool, so you don't have the issue anymore?

**Comment by TesoMayn** [comment]
Nope, once I did that it fixed everything.

My current one may have been broken.
