### ISSUE TITLE
Unabled to play music

### ISSUE THREAD

**Issue by TesoMayn** [matthieugrieger/mumbledj#53]
I get this error with every YouTube link I try

```
The audio download for this video failed. YouTube has likely not generated the audio files for this video yet. Skipping to the next song!
```

Also, what's the command to add admins?

**Comment by mkBlaze** [comment]
YouTube-DL probably isn't configured correctly.

Sent from my iPhone

On Mar 25, 2015, at 8:26 PM, Teso Mayn <notifications@github.com<mailto:notifications@github.com>> wrote:


I get this error with every YouTube link I try

The audio download for this video failed. YouTube has likely not generated the audio files for this video yet. Skipping to the next song!


Also, what's the command to add admins?

-

**Comment by matthieugrieger** [comment]
@TesoMayn: @mkBlaze is probably right. If you have it installed already, make sure it is updated to the latest version.

**Comment by TesoMayn** [comment]
It's the latest, but I think I figured it out

I think the reason it's not working is because of captcha code, because when I do youtube-dl I get

```
Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError());
```

**Comment by matthieugrieger** [comment]
Strange... I've never ran into rate limiting issues. Were you downloading a bunch of videos in a short amount of time somehow?

**Comment by TesoMayn** [comment]
Nope, it did that the first time I ran it.

I'm using a VPS from OVH, if that's at all relevant.

**Comment by matthieugrieger** [comment]
It looks like that is relevant. According to [this issue](https://github.com/rg3/youtube-dl/issues/5138) posted on the `youtube-dl` GitHub page, other people on OVH are also experiencing the issue. Maybe look through that thread and see if anything there helps?
