### ISSUE TITLE
verbose option at exec?

### ISSUE THREAD

**Issue by hamilton5** [matthieugrieger/mumbledj#56]
Configuration successfully loaded!
Could not connect to Mumble server at xxx.xxx.xx

Trying to debug, any options for this? I can connect with my client, I can ping from bots server, could connect before with mumbledj but not now, ideas?

**Comment by matthieugrieger** [comment]
There isn't currently a verbose option.

There are a few things that could prevent the bot from connecting to the server. If the server has a password, the bot will need to supply that password via the `-password` argument.

What is more likely, though, is that the certificate for the server changed. If you use the `-insecure` commandline flag when starting MumbleDJ is it able to connect?

**Comment by hamilton5** [comment]
OK, yes,  insecure worked, I was under the impression it did not even deal with certs by default. Thanks for the help!

**Comment by matthieugrieger** [comment]
Cool, glad that fixed it!

Yeah, what was happening is the certificate of the server changed, meaning it no longer matched the certificate chain found in `~/.mumbledj/cert.lock`. When the bot finds that the certificate chains differ, it cancels the connection.

**Comment by hamilton5** [comment]
so I killed all processes and removed the cert.lock file... the 2nd process I run needs the -insecure flag anyway around this? the cert.lock file holds the cert from the server, why is this needed ?

**Comment by matthieugrieger** [comment]
Are you saying that you're running multiple instances of the bot? If so, and if they are connecting to different servers, then you will need to add the `-insecure` flag because there will be differing certificate chains.

**Comment by hamilton5** [comment]
I thought you knew this? thanks will do.
