### ISSUE TITLE
Error during "make": client.go:95: undefined: tls.DialWithDialer

### ISSUE THREAD

**Issue by MartNytrm** [matthieugrieger/mumbledj#57]
Hi Matthieu, 

thanks for your awesome work! I'm pretty sure I'll enjoy mumbledj a lot if I master to do the installation.
I get the following error at the end of the "make" process:

```
[...]
compilation terminated.
=> Done!
goop go build .
# github.com/layeh/gumble/gumble
.vendor/src/github.com/layeh/gumble/gumble/client.go:95: undefined: tls.DialWithDialer
goop: Command failed with exit status 2
make: *** [mumbledj] Error 2
```

I'm not very familiar with code at all, but maybe it has something to do with a recent change in "client.go" which "layeh" (https://github.com/layeh/gumble/tree/master/gumble) has edited 9 days ago?

I hope I could help.
Thank you.

Greets

Nytrm

**Comment by matthieugrieger** [comment]
MumbleDJ uses a dependency manager called `goop` that basically freezes certain packages to a specific commit. Therefore, this issue isn't related to the changes made in `gumble`.

What version of go are you using? This error generally happens when using a go version that is not 1.3 or higher.

**Comment by MartNytrm** [comment]
Thank you very much! The Ubuntu 14.04 repos come up with version 1.2.1!
Now on Go ver. 1.4.2, no errors anymore.
Sorry for not checking my Go version, even though you explicitly mentioned it in requirements.

If you wouldn't mind, two last questions:
What bandwith does the bot use as a Mumble client? Is there a way to configure the bandwith?

Thanks for your help and time!

Greets


Nytrm

**Comment by matthieugrieger** [comment]
Great, glad that fixed it! I really wish Ubuntu would at least update their go package to 1.3. 1.2 is quite out of date.

You can see how much bandwidth the bot is using by right clicking on the bot and clicking the Information item.

There isn't currently a way to directly configure the bandwidth. However, the bot automatically scales its bandwidth to match the bandwidth of the server. So you could increase/decrease the bandwidth by increasing/decreasing the server max bandwidth.

**Comment by MartNytrm** [comment]
Thanks!
