### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MrKrucible** [matthieugrieger/mumbledj#58]
```
goroutine 503 [running]:
github.com/layeh/gumble/gumble.(*Conn).WriteAudio(0x0, 0x4, 0x0, 0x0, 0xc2083680e0, 0x70, 0x70, 0x0, 0x0, 0x0, ...)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/conn.go:84 +0x863
github.com/layeh/gumble/gumble.writeAudioTo(0xc20805e0b0, 0xc208031000, 0x1e0, 0x1e0, 0x0, 0x0, 0x0)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/audio.go:82 +0x1a2
github.com/layeh/gumble/gumble.AudioBuffer.writeMessage(0xc208031000, 0x1e0, 0x1e0, 0xc20805e0b0, 0x0, 0x0)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/audio.go:65 +0x61
github.com/layeh/gumble/gumble.(*AudioBuffer).writeMessage(0xc208158000, 0xc20805e0b0, 0x0, 0x0)
        <autogenerated>:1 +0xbd
github.com/layeh/gumble/gumble.(*Client).Send(0xc20805e0b0, 0x7fb4a9b96428, 0xc208158000, 0x0, 0x0)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:221 +0x4a
github.com/layeh/gumble/gumble_ffmpeg.(*Stream).sourceRoutine(0xc2080524e0, 0xc20802c020, 0x1, 0x1)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:148 +0x47c
created by github.com/layeh/gumble/gumble_ffmpeg.(*Stream).play
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:94 +0x479

goroutine 1 [chan receive, 14499 minutes]:
main.main()
        /home/botmaster/mumbledj/main.go:207 +0xc8d

goroutine 17 [syscall, 14500 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 509 [select]:
github.com/layeh/gumble/gumble.(*Client).pingRoutine(0xc20805e0b0)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:159 +0x2dc
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:117 +0x5f9

goroutine 508 [IO wait]:
net.(*pollDesc).Wait(0xc208368370, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208368370, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208368310, 0xc20810e000, 0x2000, 0x2000, 0x0, 0x7fb4a9b92bf0, 0xc20810a870)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c090, 0xc20810e000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2081d02a0, 0x7fb4a9b94290, 0xc20802c090, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2080a8000, 0x17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2080a8000, 0xc20810a868, 0x2, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:904 +0x166
io.ReadAtLeast(0x7fb4a9b947b0, 0xc2080a8000, 0xc20810a868, 0x2, 0x8, 0x2, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7fb4a9b947b0, 0xc2080a8000, 0xc20810a868, 0x2, 0x8, 0x4, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x6d
encoding/binary.Read(0x7fb4a9b947b0, 0xc2080a8000, 0x7fb4a9b946c8, 0xbeaad8, 0x6cab20, 0xc20810a860, 0x0, 0x0)
        /usr/local/go/src/encoding/binary/binary.go:148 +0x12d
github.com/layeh/gumble/gumble.(*Conn).ReadPacket(0xc20802aac0, 0xc20836b970, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/conn.go:46 +0x22a
github.com/layeh/gumble/gumble.(*Client).readRoutine(0xc20805e0b0)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:177 +0x93
created by github.com/layeh/gumble/gumble.(*Client).Connect
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble/client.go:116 +0x5dc

goroutine 510 [runnable]:
github.com/layeh/gumble/gumble_ffmpeg.(*Stream).sourceRoutine(0xc2080534a0, 0xc20802c0b0, 0x1, 0x1)
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:116
created by github.com/layeh/gumble/gumble_ffmpeg.(*Stream).play
        /home/botmaster/mumbledj/.vendor/src/github.com/layeh/gumble/gumble_ffmpeg/gumble_ffmpeg.go:94 +0x479
```

I do not know what could of caused the crash, but I finally got a log after it happened a couple of times.

**Comment by matthieugrieger** [comment]
I know you said that you do not know what causes the crash, but does it seem to be random? Or does it happen when starting up the bot? I've been running the current version on my server for a few days and have used it fairly often and I haven't had any issues.

**Comment by MrKrucible** [comment]
Huh, so I updated the bot just now. Though I've run into another issue with all my links giving ```The YouTube URL you supplied did not contain a valid YouTube ID.```

**Comment by matthieugrieger** [comment]
Did you follow the guide for adding a YouTube API key? If so, make sure the key has been input correctly. Also make sure that your server IP has been added to the list of accepted IPs for your server key.

**Comment by MrKrucible** [comment]
Yup, no problem with adding the API and already double checked the IP. Thing is that there's no other error coming from mumbledj.

Do I need some sort of certificate or key from Google too?

**Comment by matthieugrieger** [comment]
Nope, the YouTube API key is the only one that you need. This is strange; I have not been able to replicate this. I'll try to look into it as soon as I can.

I do plan on making some changes to MumbleDJ soon that will allow me to just distribute pre-compiled binaries, which should hopefully reduce the amount of differences between my version and versions that other people are running.

**Comment by MrKrucible** [comment]
Yea, this is the whole error and it's coming only in Mumble chat.

Just to clarify on the setup, for ```Add the IP address of your server``` do you mean the Mumble server IP or the IP for the box MumbleDJ is running on? Even so I've tried both (two different API keys) and still getting the error, but it's something that probably should be clarified.

**Comment by matthieugrieger** [comment]
It is the IP of the box the bot is running on. I'll update the README to make it more clear.

And the error comes out on Mumble chat? Not in terminal output?

**Comment by MrKrucible** [comment]
Thanks for clarifying. Using the API with that IP attached and still getting the error. There is no terminal output, just the error in Mumble chat saying ```The YouTube URL you supplied did not contain a valid YouTube ID.``` to every valid !add command.

**Comment by matthieugrieger** [comment]
Ah, that makes a lot more sense. For some reason I thought you were saying that the log you posted in your opening post was shown in chat.

You've probably told me before, but what distro are you running the bot on?

**Comment by MrKrucible** [comment]
Debain, I'm actually installing arch on a new machine for another project.

**Comment by matthieugrieger** [comment]
Alright, cool. When I get the time I will spin up a Debian box and see if I can replicate the issue on a clean install.

One last thing -- there have been instances in the past where strange networking-related issues only happened on certain hosting providers. What server host are you using, or are you just hosting on your own personal machine?

**Comment by MrKrucible** [comment]
Dedispec.com is what I'm using. It's a completely open box, not VPS.

**Comment by MrKrucible** [comment]
Alright, just installed the bot on a new VPS with Ubuntu. Now I'm getting a different error on Ubuntu, but it still effects every link !added and the error has no terminal output.

The error from Mumble chat: ``` The audio download for this video failed. YouTube has likely not generated the audio files for this video yet. Skipping to the next song!```

**Comment by matthieugrieger** [comment]
Do you have `youtube-dl` installed? This message usually shows up when you forget to install it (I forget all the time).

**Comment by MrKrucible** [comment]
Yup, already have it installed.

**Comment by matthieugrieger** [comment]
Weird. To be honest I'm a bit confused as to why you are having this issue. The bot runs fine on my end, and it seems to run fine for others as well.

What happens if you execute this in terminal?
`youtube-dl --output ~/.mumbledj/songs/test.m4a --format m4a --jfFTT3iz740`

**Comment by MrKrucible** [comment]
```botmaster@debian:~$ youtube-dl --output ~/.mumbledj/songs/test.m4a --format m4a --jfFTT3iz740
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: --jfFTT3iz740
```

**Comment by matthieugrieger** [comment]
Make sure you have the most up-to-date version of `youtube-dl`. I believe the older versions do not support the `--` commandline argument.

**Comment by MrKrucible** [comment]
Okay, went grabbed it with wget. Now the output is blank, so I guess it's being written. I've tried loading up the bot again but still getting the original error.

```botmaster@debian:~/mumbledj$ youtube-dl --output ~/.mumbledj/songs/test.m4a --format m4a --jfFTT3iz740
botmaster@debian:~/mumbledj$
```
Then in Mumble chat...
```[12:51:59 AM] To S: !add https://www.youtube.com/watch?v=4cq--Eay9Uo
[12:52:00 AM] Kirk: The YouTube URL you supplied did not contain a valid YouTube ID.
```

**Comment by matthieugrieger** [comment]
Okay, sounds good.

Maybe at some point test whether the following link works? There is a possibility that the "--" in the ID of the YouTube video you added messed up the add command.

https://www.youtube.com/watch?v=zel2H9M7A38

**Comment by MrKrucible** [comment]
Wow, it works on Arch. No errors. Have you tried it on a Debian or Ubuntu system yet, or is anyone viewing currently running the latest MumbleDJ in one of those distros?

**Comment by matthieugrieger** [comment]
I've been running it on my Ubuntu server for the past few months, never had
an issue with it.

**Comment by MrKrucible** [comment]
Well, turns out I have the same issue with #53 and my host said they are also blocked in the same fashion. So the only way to fix this is forcing youtube-dl to use the ```--force-ipv4 , -4``` argument on all the songs mumbledj downloads.

I fixed it by following the instructions here to set default arguments: https://github.com/rg3/youtube-dl/blob/master/README.md#configuration

For the lazy...
- 1. First make ```~/.config/youtube-dl/``` and create a file named ```config```.
- 2. Then put ```--force-ipv4``` into the config. Nothing else needs to be in there unless you want to add more arguments.

Matt, should there just be a trouble-shoot section for this in the ```README.md``` for this type of stuff?

**Comment by matthieugrieger** [comment]
Great, glad you figured it out!

Yes, I've been meaning to add a Troubleshooting/FAQ section in the README for awhile now. This would be a great addition. I will make it a priority.
