### ISSUE TITLE
Error while trying to compile

### ISSUE THREAD

**Issue by Xephi** [matthieugrieger/mumbledj#60]
Hi ! I've got that kind of error while i'm trying to compile the project : 

go get github.com/nitrous-io/goop
\# github.com/nitrous-io/goop/parser
/root/go/src/github.com/nitrous-io/goop/parser/parser.go:32: undefined: bufio.NewScanner
\# code.google.com/p/go.tools/go/vcs
/root/go/src/code.google.com/p/go.tools/go/vcs/discovery.go:20: function ends without a return statement
/root/go/src/code.google.com/p/go.tools/go/vcs/discovery.go:31: function ends without a return statement
make: *** [mumbledj] Error 2

**Comment by matthieugrieger** [comment]
What version of go do you have installed?

**Comment by Xephi** [comment]
Hi! I got go1.4.2 for amd64 (already tested for 32bits too, same problem :/)

**Comment by matthieugrieger** [comment]
That is strange if you are experiencing this error while running 1.4.2. I would first recommend reinstalling go. Generally these errors occur when using an outdated version of go, so it shouldn't happen if you're running the latest version.

Let me know if you still experience issues after reinstalling.

**Comment by Xephi** [comment]
I've done that : 
rm -rf /root/go
wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
tar xzf go1.4.2.linux-amd64.tar.gz (in /root dir)
export GOPATH=/root/go
export PATH=$PATH:$GOPATH/bin

**Comment by Xephi** [comment]
It works now... just after a reboot off the server ... idk why T.T thanks anyway for your quick answer >.<

**Comment by matthieugrieger** [comment]
Well at least it works now! Let me know if there are any more issues.
