### ISSUE TITLE
The YouTube URL you supplied did not contain a valid YouTube ID.

### ISSUE THREAD

**Issue by Xephi** [matthieugrieger/mumbledj#61]
It appears i can't download any youtube video
but when i try youtube-dl <thatlink>
it works :/
i've try with some links, like https://www.youtube.com/watch?v=rRkS7CdbxD8

**Comment by matthieugrieger** [comment]
Hmm.. I'm not quite sure why there are so many issues with YouTube now. I'm guessing it is somehow related to the YouTube API v3 update.

I'll have to look into this.

**Comment by Xephi** [comment]
i just needed to put the ipv4 directly in youtube api, idk why it doesn't work with ipv6 anymore for my server, it seems fixed, sorry for that useless report :(

**Comment by matthieugrieger** [comment]
Ah, that's interesting. No worries! This is something that someone else might struggle with, so it is nice to have a record of how this issue is fixed.

**Comment by hamilton5** [comment]
I simply had the wrong IP setup in the youtube api - thanks for this.
