### ISSUE TITLE
Multiple Alias and helpfile

### ISSUE THREAD

**Issue by branklam** [matthieugrieger/mumbledj#63]
Hiya-

Because I'm lazy, I wanted to change !currentsong to !wtf, got this to work but currentsong no longer works.  Not a huge issue, but maybe allow multiple alias' per command?

Also, I didn't see how to edit the !help document to reflect the changes to alias' in the gcfg file (either manually or via !reload).

Love mumbledj so far, thanks a bunch!

**Comment by matthieugrieger** [comment]
While having multiple aliases for the same command is a good idea, I think that it would unnecessarily complicate the code.

However, the issue with the `!help` command is something I have planned on implementing for quite awhile now. I am considering changing how the bot configuration works, so I'll probably include that change when I mess with it.

**Comment by matthieugrieger** [comment]
Multiple aliases are now supported in v3.0.0, and the `!help` command is updated accordingly.
