### ISSUE TITLE
[Feature] Support for starting at a specified time (&t=XXmXXs)

### ISSUE THREAD

**Issue by RichardNysater** [matthieugrieger/mumbledj#65]
Hi, first I'd like to say that mumbledj is a great software which has worked flawlessly for me.

However, it would be great if there was support for Youtube's "start at XX:XX" feature (e.g: https://www.youtube.com/watch?v=VbxgYlcNxE8&t=14m05s) since many songs (and other clips) has an irrelevant intro.

**Comment by matthieugrieger** [comment]
I'm glad MumbleDJ has been working fine for you.

This is something that has been brought up in the past, and while it is a good idea, I don't know if it can easily be implemented. I'll look through the `youtube-dl` documentation at some point and see if there is an easy way to do this.

**Comment by bontibon** [comment]
@matthieugrieger I'm thinking a modification of gumble_ffmpeg could help solve this. You can follow the ticket (layeh/gumble#14) here.

**Comment by matthieugrieger** [comment]
@bontibon: Sweet.

**Comment by matthieugrieger** [comment]
@RichardNysater: @bontibon has updated `gumble` to support this behavior. I will try to get an update out to implement this as soon as I can. :)

**Comment by RichardNysater** [comment]
@matthieugrieger That's awesome! This means a lot more youtube clips can be played, the users on my mumble will be glad to use this, I'm sure.

**Comment by matthieugrieger** [comment]
Alright, this should be added in now. Let me know if there are any issues!
