### ISSUE TITLE
[Feature Request] Player Anthems

### ISSUE THREAD

**Issue by Kamori** [matthieugrieger/mumbledj#66]
User Anthems:

This was suggested by one of my buddies. Its something I've been thinking about adding in myself (Trying to learn GoLang) But wanted some feedback on the idea and logging it. Player Anthems would essentially be short clips of audio that remain cached on the server that play when a player enters the channel. Each person can set their own anthem to play when they join.

Technical details - Plan is to store in a sqllite db in the ~/.mumbledj directory a list of users and song names. Upon player join channel scan the sqllite db to see if they're listed in the table. upon sql select response play the expected song from the filesystem for xx period of time. (If possible fade out the volume at the end)

**Comment by matthieugrieger** [comment]
Interesting idea! Unfortunately this isn't something that I would add in to MumbleDJ.

However, feel free to ask me questions here if you'd like! Here's how I would go about it:

Add a `!setanthem` command that takes a YouTube URL as its argument. The audio for the YouTube video is then downloaded and placed in a "player anthems" directory. The user could then be linked to the anthem using a SQLite database or a simple comma separated text file. Another solution would be to rename the downloaded file to match the username of the user who made the request. This would only work (correctly) on servers where all users are authenticated. Also, add a length limit for the input data to `!setanthem`.

Besides using a timer I don't know of a good way to stop the audio after X amount of time. It would likely be fairly inconsistent. Also, there is a potential conflict when the bot is already playing music and somebody enters the channel and has an anthem played.

Hopefully this helps somewhat. I will close this issue but feel free to let me know if you have any questions about the implementation.
