### ISSUE TITLE
New Build Error

### ISSUE THREAD

**Issue by MrKrucible** [matthieugrieger/mumbledj#69]
Started a fresh install on another user so my bots could have different admins, and got a build error in ```make```
```
=> Done!
goop go build
# _/home/mumbledj0/mumbledj
cannot create <nil>/go.o: No such file or directory
goop: Command failed with exit status 2
make: *** [mumbledj] Error 2
```
Go version is 1.4.2, is there something specific that causes this?

**Comment by matthieugrieger** [comment]
What happens if you execute the following before building?

```export TMPDIR=/tmp```

**Comment by MrKrucible** [comment]
Yup, that worked! Thanks a lot!

Another thing to add to Troubleshoot?

**Comment by matthieugrieger** [comment]
Yep! Glad it fixed it.
