### ISSUE TITLE
`panic: runtime error: index out of range` with specific playlist

### ISSUE THREAD

**Issue by mkody** [matthieugrieger/mumbledj#70]
MumbleDJ v.2.7.3 crashes when we add this playlist: [youtube.com/playlist?...](https://www.youtube.com/playlist?list=PLOP4OcXrhLdz26EW5LAfQjsc1UVcrOPoo)

Here's the log: https://gist.github.com/mkody/aa0b2f1b3e7fcf3f173f

**Comment by matthieugrieger** [comment]
Thanks! I will take a look at this as soon as possible.
