### ISSUE TITLE
request: user configurable max playlist

### ISSUE THREAD

**Issue by zeblau** [matthieugrieger/mumbledj#71]
It would be nice to have an option to change the hard limit of 25 to something higher or lower.

**Comment by matthieugrieger** [comment]
Yes, this is something I have been meaning to change. I believe the limit of 25 is a remnant of the limitations of the YouTube v2 API.

**Comment by GabrielPlassard** [comment]
Currently the limit is at 50 items (and the youtube api doesn't seem to allow to retrieve more at once : https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.playlists.list

I'm trying to implement a way to make as much api calls as needed, but a max size config might also be usefull.

**Comment by matthieugrieger** [comment]
Yeah they increased the limit to 50 when they rolled out their new API.

The `pageToken` field in the API response would probably be helpful in doing these larger API calls.
