### ISSUE TITLE
request: command line argument to display version of mumbledj

### ISSUE THREAD

**Issue by zeblau** [matthieugrieger/mumbledj#72]
Although it is easy to update sources and build again, it would be nice to have a -v or --version command line argument which exits after displaying the current version of mumbledj.

**Comment by matthieugrieger** [comment]
Good idea! I will get to this as soon as possible.

**Comment by zeblau** [comment]
Hi I have prepared a commit for this (both command line version info and one in chat that the bot responds to). I could push it to master. Just let me know.

**Comment by matthieugrieger** [comment]
Awesome! Make up a pull request and I'll take a look. :)

**Comment by DudeofA** [comment]
Hey! You closed this issue! Show your pride! :D

**Comment by matthieugrieger** [comment]
Whoops, thanks. :)
