### ISSUE TITLE
Cannot make - error in cache.go

### ISSUE THREAD

**Issue by adeleglise** [matthieugrieger/mumbledj#73]
Hi, I'm currently trying to install mumbledj.

When it comes to the "make" part, it fails with an error on line 85 and 100 of the "cache.go" file :

```bash
goop go build
# _/root/mumbledj
./cache.go:85: syntax error: unexpected range, expecting {
./cache.go:100: syntax error: unexpected }
goop: Command failed with exit status 2
Makefile:4: recipe for target 'mumbledj' failed
make: *** [mumbledj] Error 2
```
I can provide the full stdout of the make if needed.

Thanks.

**Comment by adeleglise** [comment]
Ok my bad.

I was using go 1.3 ...

I suggest you add the gvm tool to your install http://www.hostingadvice.com/how-to/install-golang-on-ubuntu/

As i am using the golang package on Debian, it was installed in 1.3, using gvm I was able to easily switch to go 1.4

Thanks.

**Comment by matthieugrieger** [comment]
I wasn't aware of gvm. However I don't think that is something that should be included with MumbleDJ. I'll try to remember to add a note about it in the README though.

**Comment by adeleglise** [comment]
Yeah, I meant it that way :) 

Although, I assume the fact that i've read your readme but didn't payed attention to the go version as I was using the package provided by the Debian repo. 

So now that MumbleDJ is working for me, I can tell that it's really a great tool ! Kudos to you ^^

**Comment by matthieugrieger** [comment]
Cool. I think part of the problem is that the required go version is somewhat hidden within the installation instructions. I need to make a separate dependencies section that just lists the required dependencies explicitly and clearly.
