### ISSUE TITLE
Process quits silently.

### ISSUE THREAD

**Issue by Pherr** [matthieugrieger/mumbledj#74]
I installed MumbleDJ and it was working until I rebooted.
Now when I try to start it says 
`Configuration successfully loaded!`
and then exits.

**Comment by matthieugrieger** [comment]
Does it disconnect immediately after showing the configuration message? I haven't encountered this before.

**Comment by Pherr** [comment]
As far as I can tell it doesn't connect at all, the configuration message is the only output.

**Comment by matthieugrieger** [comment]
Whoops, what I meant to ask is if the process exits immediately after showing the configuration message. Based on your response I'm guessing that is the case?

**Comment by Pherr** [comment]
It hangs for a few seconds but there's no more output.

**Comment by matthieugrieger** [comment]
Got it. At the moment I'm not quite sure why this is happening; I'll have to look into it.

**Comment by Pherr** [comment]
I don't know if it helps but I'm running it on a Raspberry Pi.

**Comment by matthieugrieger** [comment]
Although this is not directly related to your issue, I should let you know that people have had problems in the past running the bot on a Raspberry Pi.

The audio transcoding that MumbleDJ does is fairly CPU intensive and people have had issues with the Pi being able to keep up.

It is possible that the Pi is causing this issue as well, but I'm not quite sure what would be causing it.

**Comment by Pherr** [comment]
Is there some sort of log file I should look at to see what's going wrong?

**Comment by matthieugrieger** [comment]
Unfortunately there isn't at the moment. It is on the to-do list to implement a debug mode for MumbleDJ.

**Comment by Pherr** [comment]
So it turns out this was entirely my fault.
I forgot that I changed the Mumble server password and wasn't using the new password when starting MumbleDJ.

**Comment by matthieugrieger** [comment]
No worries, glad you figured it out!

**Comment by Pherr** [comment]
You might be interested in knowing that if you overclock the Raspberry Pi to the "Turbo" setting it's enough to run MumbleDJ without issues. But if you're also running the Mumble server on the Raspberry Pi the music will get choppy if anyone talks.

**Comment by matthieugrieger** [comment]
That is good to know, thanks! I will try to remember to add a note about it in the README. Quite a few people have tried to get the bot working on the Raspberry Pi.
