### ISSUE TITLE
Problem with API Key and systemd

### ISSUE THREAD

**Issue by Saphareas** [matthieugrieger/mumbledj#75]
Hi,
I'm running mumbledj on Arch Linux which uses systemd. Somehow, when I simply run the command `mumbledj` it works fine, but when I'm trying to start mumbledj as a Service using `systemctl start mumbledj` it says `You do not have a YouTube API key defined in your environment variables.`

**Comment by matthieugrieger** [comment]
Hey there,

This is likely an issue with how you configured your `systemd` service. I ran into a similar problem with `upstart` on Ubuntu. Try referring to the following link to see if it solves your issue: http://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service

Let me know if you get it working!

**Comment by Saphareas** [comment]
Thanks,
now it's working like a charm. Really great piece of Software you created here :)

**Comment by matthieugrieger** [comment]
No problem. :)
