### ISSUE TITLE
MumbleDJ just ain't playing.

### ISSUE THREAD

**Issue by tjhorner** [matthieugrieger/mumbledj#79]
Running latest (#6415a597daa028cc2ed3d3e37035324972ea8dbc) version of MumbleDJ on Fedora 21 Server.

Starts up fine, no errors when adding songs, they're downloaded in `~/.mumbledj/songs` and open when I play them. Looked at the troubleshooting guide in the README. Any ideas of what could be going on?

**Comment by tjhorner** [comment]
Fuck, duplicate, sorry.

**Comment by matthieugrieger** [comment]
No worries. Did you get it working?
