### ISSUE TITLE
Audio cutting out

### ISSUE THREAD

**Issue by caindrac** [matthieugrieger/mumbledj#8]
I see that someone was having this problem previously but it does not look like it was resolved for him. I was just wandering if anyone else was having this problem and knows how to fix it.

**Comment by matthieugrieger** [comment]
Hi!

I'll need a little more information. What are you running MumbleDJ on? What distro? Is it on the same machine as your Mumble server?

I've tested MumbleDJ both on a local server on my desktop, and my personal Mumble server which I host on a server, works fine on both.

**Comment by caindrac** [comment]
I have figured out the problem. I believe that it has to do with my vps's IO speed. Moved it to a different server and it fixed it.

**Comment by caindrac** [comment]
Well now it is doing it again Digital Ocean Debian 64 bit.

**Comment by matthieugrieger** [comment]
Strange. Your setup is very similar to mine (Ubuntu 14.04 on DigitalOcean).

There is a possibility that the problem comes from the receiving end. There have been times occasionally where I have a slow connection and the audio starts to cut out.

Did you change any of the audio settings (codec, bit rate) while setting up your Mumble server?

**Comment by caindrac** [comment]
Nope it is the standard codec and bit rate. I don't normally change anything with the install unless it is needed.

**Comment by matthieugrieger** [comment]
You must have it set up like I have it set up then. So you don't receive any crashes or have troubles with other portions of the bot not working?

It is fairly common in my experience to have periods of time where the audio cuts in and out slightly, and my friends experience it sometimes as well. It doesn't happen that often though, so it is hard for me to determine what is causing the issue.

**Comment by caindrac** [comment]
Well I have been test for the last few hours and cant get one song to not cutout. I just trying to get it work most of the time.

**Comment by caindrac** [comment]
Sweet, this looks like it fixed it! Thanks for all the help and great work on this DJ. Before I found the project I thought I was going to have to code up my own.

**Comment by matthieugrieger** [comment]
Awesome, I'm glad this fixed it and that you like the bot! Let me know if there are any other issues.
