### ISSUE TITLE
Most songs return audio download for this video failed when added.

### ISSUE THREAD

**Issue by mistahnice** [matthieugrieger/mumbledj#83]
Ever since about last month, it seems like 50-75% of youtube videos once added return "The audio download for this video failed. YouTube has likely not generated the audio files for this video yet. Skipping to the next song!". 

We've updated to the latest version. Attached is my attempt to play some Peter Gabriel mostly unsuccessfully. 

![image](https://cloud.githubusercontent.com/assets/13975816/9486323/48b51282-4b8b-11e5-8cf0-a156fd5d7484.png)

**Comment by matthieugrieger** [comment]
This has been happening to me too, I've been meaning to look into it but I've been pretty busy lately. I'm pretty sure it has something to do with `youtube-dl`. I might have to mess around with some commandline options to see if anything fixes the issue.

I will hopefully get to it this weekend.

**Comment by MichaelOultram** [comment]
Have you tried clearing the youtube-dl cache using `rm -r ~/.cache/youtube-dl`?

**Comment by mistahnice** [comment]
I will try to update youtube-dl and clear the cache and report back. Thank you.

**Comment by mistahnice** [comment]
Fixed via this issue with youtube-dl https://github.com/rg3/youtube-dl/issues/6687. Thanks Dylan Taft.

**Comment by matthieugrieger** [comment]
Ah, so doing `youtube-dl --rm-cache-dir` fixed your problem?

**Comment by mistahnice** [comment]
Yes, updated some codecs as well. These two things seem to have fixed my issue entirely.

**Comment by matthieugrieger** [comment]
Cool. Hopefully it won't pop up again. Maybe I will add something to the `Makefile` that updates `youtube-dl` and clears its cache whenever you update MumbleDJ.
