### ISSUE TITLE
Issue with "tagged" videos

### ISSUE THREAD

**Issue by doppletronica** [matthieugrieger/mumbledj#86]
I've been having an intermittent issue where when I try to play tagged videos (aka videos that have been tagged as containing a song) where they don't play properly in mumbledj. It returns the "audio download has failed" error. Videos that aren't tagged play just fine. Do you know if this is an API issue or something else?

**Comment by matthieugrieger** [comment]
I haven't come across this before. Can you give me a link to an example so I can try it out on my end?

**Comment by doppletronica** [comment]
Nevermind about this. Just had to update youtube-dl in the end to get this fixed.

**Comment by matthieugrieger** [comment]
Cool, glad you fixed it!
