### ISSUE TITLE
2.8.0 Soundcloud Integration

### ISSUE THREAD

**Issue by raz0rsdge** [matthieugrieger/mumbledj#89]
Installed new MumbleDJ today on CentOS via git pull after adding a soundcloud api key to .bashrc.
Installation went fine, but on every soundcloud playlist or track URL it gives me errors like this:
<code type="bash">
!add https://soundcloud.com/solebicycles/sole-fixtape-vol-38-light-year
MumbleDJ: The URL you submitted does not match the required format.

!add https://soundcloud.com/raz0rsedge/sets/sleephealing
MumbleDJ: The URL you submitted does not match the required format.
</code>

Anyone else run into it?

**Comment by raz0rsdge** [comment]
Okay solved after third login and restart via:

<code>
#!/bin/bash
mumbledj -server=localhost -port=64999 -username=MumbleDJ -password="" -channel=Music -cert="mumbleDJ-Cert.pem" -key="mumbleDJ-Key.pem" >log/mumbledj.log &
# >/dev/null 2>&1 &
</code>

Now getting this:
<code>
[18:13:07] (Kanal) MumbleDJ: The audio download for this video failed. %s has likely not generated the audio files for this %s yet. Skipping to the next song!
</code>

**Comment by MichaelOultram** [comment]
I'm assuming youtube tracks work?

**Comment by raz0rsdge** [comment]
yepp, sry forgot to mention that

**Comment by raz0rsdge** [comment]
while for youtube in the songs dir .m4a files are created, for soundcloud nothing appears...

**Comment by MichaelOultram** [comment]
Maybe try updating youtube-dl. I know that they had an issue with soundcloud recently which should be now fixed rg3/youtube-dl#6930

**Comment by raz0rsdge** [comment]
OMG, fixed with 
<code>
youtube-dl -U
</code>

didn't realize that this was not set up by go... sry!

**Comment by MichaelOultram** [comment]
No problem, glad you got it working.

**Comment by matthieugrieger** [comment]
Thanks for helping out @MichaelOultram.

Yeah, for some reason SoundCloud audio does not download correctly until it is updated. I need to fix that error message, it seems that the string is not being formatted properly.
