### ISSUE TITLE
Question about a possible New Function

### ISSUE THREAD

**Issue by caindrac** [matthieugrieger/mumbledj#9]
Is it possible for you to add command that will clear the whole que but not remove the bot from mumble. Basically !kill command with out the disconnect.

**Comment by matthieugrieger** [comment]
@caindrac: This is actually a feature that I was going to implement at some point! I will make sure that I include it in the next release.

**Comment by caindrac** [comment]
Thanks

**Comment by matthieugrieger** [comment]
@caindrac: I added this with this commit: https://github.com/matthieugrieger/mumbledj/commit/158618024626407c93745c670f82b4e6e54b026f. Let me know if there are any issues!
