### ISSUE TITLE
[Feature] Custom Config Location

### ISSUE THREAD

**Issue by Kamori** [matthieugrieger/mumbledj#97]
As i've been setting up my server to house my MumbleDJ i'm trying to make it more available. I've run into the need for being able to define a custom config location so they don't sit on the /home partition. This also goes for the song cache. 

Essentially looking for a 

```
mumbledj -c /etc/mumbledj/mumbledj.gcfg
```

Along with that is the request to add config options for defining the locations of

songs

And the server connection details so the script itself doesn't have to be executed with command line args but also by parsing config options.

**Comment by matthieugrieger** [comment]
All of these things are planned as changes that will be made in the refactor that I am currently trying to find time to work on. :)

**Comment by matthieugrieger** [comment]
A custom config location can now be provided with the `--config` flag as of v3.0.0.
