### ISSUE TITLE
Make fails at installation

### ISSUE THREAD

**Issue by RCambier** [matthieugrieger/mumbledj#98]
I tried upgrading my MumbleDj to include soundcloud support, but it failed (Some problems with Go version).
Now I tried to re-install from scratch and I have this problem when executing "goop install":

[...]
=> Fetching code.google.com/p/gcfg...
Makefile:4: recipe for target 'mumbledj' failed
make: *** [mumbledj] Segmentation fault

I tried various things, but nothing worked.

**Comment by matthieugrieger** [comment]
Strange, haven't seen this yet. What version of Go are you running? Did you install it manually or via a distribution repository?

**Comment by RCambier** [comment]
I have go 1.4.2
I tried both ways, with go installed via apt-get and by downloading from the website.

**Comment by matthieugrieger** [comment]
Awesome, glad you figured it out!
